Customer personas (first draft)
stackabletech/documentation pull request #105
Opened 2021-10-28 11:52 UTC by teozkr

Based on what we came to in today's meeting (https://docs.google.com/document/d/1K6BIvARKWpum1XJ2rveYbJGK4s1cyOMxnuCj_QyjKyU/edit#) but cleaned up slightly.

Created a new internal section for this stuff. Probably want to move the ADRs into it as well at some point, but I'm not really sure about whether this is the correct way to manage it.

2021-11-02 13:13 UTC, soenkeliebau requested changes
Left some questions and one (nitpicking) correction. 

One general question, there is no distinction between inside/outside access to our services, we are assuming outside access is always necessary?

2021-11-02 13:13 UTC, soenkeliebau commented on modules/internal/pages/personas.adoc
> +    Does the customer want us to integrate into their existing Kerberos realm?
Maybe briefly mention trusts and if they are an option?

2021-11-02 13:13 UTC, soenkeliebau commented on modules/internal/pages/personas.adoc
> +Kubernetess cluster::
```suggestion
Kubernetes cluster::
```

2021-11-02 13:13 UTC, soenkeliebau commented on modules/internal/pages/personas.adoc
> +    How long can a single node identity be expected to last for? (Years, weeks, days, hours)
This mainly refers to the hostname of the node?

2021-11-02 13:13 UTC, soenkeliebau commented on modules/internal/pages/personas.adoc
> +    ???
For all intents and purposes we can assume "no" here I believe. I've not yet seen anybody follow through on SeLinux..
@lfrancke  ?

2021-11-02 13:32 UTC, teozkr commented on modules/internal/pages/personas.adoc
> +Kubernetess cluster::
Oops.

2021-11-02 13:34 UTC, teozkr commented on modules/internal/pages/personas.adoc
> +    How long can a single node identity be expected to last for? (Years, weeks, days, hours)
Hostname, IP address, local disks, etc.

2021-11-02 13:35 UTC, teozkr commented on modules/internal/pages/personas.adoc
> +    Does the customer want us to integrate into their existing Kerberos realm?
I don't think I'm familiar enough to write a reasonable question here, but feel free to suggest something.

2021-11-05 08:46 UTC, lfrancke commented on modules/internal/pages/personas.adoc
> +    ???
Agreed

2021-11-05 11:25 UTC, teozkr commented on modules/internal/pages/personas.adoc
> +    ???
Ok, changed this to no then.

2021-11-05 11:31 UTC, teozkr commented on modules/internal/pages/personas.adoc
> +    How long can a single node identity be expected to last for? (Years, weeks, days, hours)
Added a note about this to the doc

2021-11-19 16:12 UTC, soenkeliebau commented on modules/internal/pages/personas.adoc
> +    Does the customer want us to integrate into their existing Kerberos realm?
```suggestion
    Does the customer want us to integrate into their existing Kerberos realm, if so is it an option to run our own kdc and integrate via trusts? 
```

2021-12-03 15:25 UTC, soenkeliebau approved these changes

2021-12-03 15:30 UTC, soenkeliebau commented
paging Mr. Antora (aka @lfrancke ) regarding the conflict in the antora part of the pr :)

2021-12-03 16:14 UTC, lfrancke commented
That's prerry straightforward. The antora.yml has changed. This just needs a manual resolve but that is easy.
We used to have multiple entries in there, now we only have one. Just add this new one at the end.

2021-12-10 08:30 UTC, lfrancke approved these changes

2021-12-13 14:38 UTC, merged