Updated getting started guide for reworked operators
stackabletech/documentation pull request #135
Opened 2022-02-04 11:52 UTC by Jimvin

and for installation on both Kind and K3s

2022-02-04 21:22 UTC, lfrancke requested changes

2022-02-04 21:22 UTC, lfrancke commented on modules/ROOT/pages/getting_started.adoc
> +##
Intentional?

2022-02-04 21:22 UTC, lfrancke commented on modules/ROOT/pages/getting_started.adoc
> +With Helm installed you can add the Stackable operator repo, where the helm charts to install Stackable operators can be found. There are development, test and a stable repositories available, we'll
I think test doesn't make much sense.
The test repo is now only used for PRs so here you'll get the code of a random PR.
The dev repo is the latest version from main, that makes more sense I believe.

2022-02-04 21:22 UTC, lfrancke commented on modules/ROOT/pages/getting_started.adoc
> +helm install nifi-operator stackable-test/nifi-operator --version=0.5.0-pr160 --devel
This should probably wait until it's finally in main :)

2022-02-07 07:13 UTC, backstreetkiwi commented on modules/ROOT/pages/getting_started.adoc
> +With Helm installed you can add the Stackable operator repo, where the helm charts to install Stackable operators can be found. There are development, test and a stable repositories available, we'll
Perhaps it would make even more sense to only refer to the stable repo in the Quickstart Guide? The nightly builds can be unstable at times as well and for a first glimpse at Stackable, stability would be worth more than having the bleeding edge software IMHO.

2022-02-07 07:20 UTC, backstreetkiwi requested changes
very helpful guide, just some minor typos and my 2 cents on the helm-dev discussion...

2022-02-07 07:20 UTC, backstreetkiwi commented on modules/ROOT/pages/getting_started.adoc
> +Since this is the first time that each of these services has been deployed to these nodes the Stackable Agent needs to download the software from the Stackable repository. It may take a few minutes t
"ing" -> "in"

2022-02-07 07:20 UTC, backstreetkiwi commented on modules/ROOT/pages/getting_started.adoc
> +Browse to the address of one of your node on port 30247 e.g. https://quickstart.local:30247/nifi and you should see the NiFi login screen.
"node" -> "nodes"

2022-02-07 07:20 UTC, backstreetkiwi commented on modules/ROOT/pages/getting_started.adoc
> +The Apache NiFi operator will automatically generate the admin user credentials with a random password and stored it as a Kubernetes secret in order to provide some security out of the box. You can r
"stored" -> "store"

2022-02-10 10:50 UTC, teozkr commented on modules/ROOT/pages/getting_started.adoc
> +With Helm installed you can add the Stackable operator repo, where the helm charts to install Stackable operators can be found. There are development, test and a stable repositories available, we'll
:+1:

2022-02-14 13:21 UTC, maltesander commented on modules/ROOT/pages/getting_started.adoc
> +      nodePort: 31000
The default `https` port now is `8443`. And that service is created automatically from the operator? Additionally there should be a nifi znode be deployed as well as the secrets (https://github.com/stackabletech/nifi-operator/blob/main/examples/simple-nificluster.yaml)?

2022-02-15 16:10 UTC, Jimvin commented on modules/ROOT/pages/getting_started.adoc
> +      nodePort: 31000
Updated the guide to use the new example template for NiFi.

2022-02-17 12:09 UTC, lfrancke approved these changes

2022-02-18 15:48 UTC, merged