ADR draft: product image versioning
stackabletech/documentation pull request #146
Opened 2022-02-23 15:15 UTC by teozkr

Based on the discussion from today's architecture review meeting.

2022-02-23 21:06 UTC, soenkeliebau commented on modules/contributor/pages/adr/drafts/ADRx-product_image_versioning.adoc
> +* Bad, because it increases the complexity of the operators even further
I have quite frankly stopped caring about this, if we can solve it properly once and manage to hide the complexity of resolving this in the framework ... so be it.

2022-02-23 21:06 UTC, soenkeliebau commented on modules/contributor/pages/adr/drafts/ADRx-product_image_versioning.adoc
> +* Bad, because it slows down reconciliation
Due to the external call to the registry?

2022-02-23 21:08 UTC, soenkeliebau commented on modules/contributor/pages/adr/drafts/ADRx-product_image_versioning.adoc
> +* Bad, because existing operators will switch which (minor-level) image version they deploy without user action
Could we make this configurable by keeping the currently deployed image hash in the cluster status and allowing the user to configure whether the image version may be automatically updated?
Going a bit further, we could also track when we last checked for updates and allow defining a delay before the next check, that might help with delaying the reconciliation as well.

2022-02-23 21:10 UTC, soenkeliebau commented on modules/contributor/pages/adr/drafts/ADRx-product_image_versioning.adoc
> +* Bad, because we don't have a good trigger for when new image versions are released
Basically we'd just need to check (see above for ideas on how to mitigate the overhead a bit) on every reconciliation and hope that one is triggered every so often?

2022-02-23 21:10 UTC, soenkeliebau commented on modules/contributor/pages/adr/drafts/ADRx-product_image_versioning.adoc
> +* Bad, because on-prem registry mirrors may not have whatever API or metadata we need to perform this resolution
And here I was hoping there'd be a common api for this ..

2022-02-23 21:23 UTC, teozkr commented on modules/contributor/pages/adr/drafts/ADRx-product_image_versioning.adoc
> +* Bad, because it slows down reconciliation
Yep

2022-02-23 21:30 UTC, teozkr commented on modules/contributor/pages/adr/drafts/ADRx-product_image_versioning.adoc
> +* Bad, because existing operators will switch which (minor-level) image version they deploy without user action
Falling back is an alternative, but there's a tricky balancing act here between stability, predictability and ensuring that we're running in a supported configuration.

2022-02-23 21:31 UTC, teozkr commented on modules/contributor/pages/adr/drafts/ADRx-product_image_versioning.adoc
> +* Bad, because we don't have a good trigger for when new image versions are released
Either that, start doing interval requeues, or have an API somewhere for querying whether there's a new release available.

2022-02-23 21:33 UTC, lfrancke commented on modules/contributor/pages/adr/drafts/ADRx-product_image_versioning.adoc
> +* Bad, because on-prem registry mirrors may not have whatever API or metadata we need to perform this resolution
You're clearly new to IT.
I have some more surprises for you then!

2022-02-23 21:39 UTC, teozkr commented on modules/contributor/pages/adr/drafts/ADRx-product_image_versioning.adoc
> +* Bad, because on-prem registry mirrors may not have whatever API or metadata we need to perform this resolution
Looks like [there is a common API](https://docs.docker.com/registry/spec/api/#listing-image-tags). I don't think it's strictly required for `docker pull` so I suspect not all registries support it... That said, [NXRM seems to](https://docker.stackable.tech/v2/stackable/kafka/tags/list), which is encouraging.

2022-02-23 21:41 UTC, soenkeliebau commented on modules/contributor/pages/adr/drafts/ADRx-product_image_versioning.adoc
> +* Bad, because existing operators will switch which (minor-level) image version they deploy without user action
Not sure I understand what do you mean by "falling back" in your comment?

2022-02-23 21:41 UTC, soenkeliebau commented on modules/contributor/pages/adr/drafts/ADRx-product_image_versioning.adoc
> +* Bad, because on-prem registry mirrors may not have whatever API or metadata we need to perform this resolution
yeah..

2022-02-23 21:41 UTC, soenkeliebau commented on modules/contributor/pages/adr/drafts/ADRx-product_image_versioning.adoc
> +* Bad, because we don't have a good trigger for when new image versions are released
We could externalize this into a stackable operator that works across all services deployed by us, which performs a regular check and triggers a requeue for anything that has a new image available..

2022-02-23 21:51 UTC, soenkeliebau commented on modules/contributor/pages/adr/drafts/ADRx-product_image_versioning.adoc
> +* Bad, because on-prem registry mirrors may not have whatever API or metadata we need to perform this resolution
Would have been awesome if that api allowed restricting which tags to get, instead of just supporting "give me everything"..

Kinda makes one think of caching that response in a component we control somewhere..

2022-02-24 09:13 UTC, teozkr commented on modules/contributor/pages/adr/drafts/ADRx-product_image_versioning.adoc
> +* Bad, because existing operators will switch which (minor-level) image version they deploy without user action
Using a cached "current version" either rather than querying the registry, or because the registry is unavailable.

2022-02-24 09:17 UTC, teozkr commented on modules/contributor/pages/adr/drafts/ADRx-product_image_versioning.adoc
> +* Bad, because we don't have a good trigger for when new image versions are released
I'm not sure how much we'd gain from that. I'd rather not teach one operator about all of our product CRD types (we've been through that dependency hell once already :P), and [Docker's Registry API](https://docs.docker.com/registry/spec/api/#detail) doesn't have an endpoint for "give me all tags for everything you know about", so we wouldn't save much network traffic by centralizing this into one component.

2022-02-24 12:10 UTC, siegfriedweber reviewed
All differences between #147 and this pull request outlined.

2022-02-24 12:10 UTC, siegfriedweber commented on modules/contributor/pages/adr/drafts/ADRx-product_image_versioning.adoc
> +Each operator version hard-codes exactly one image version that it supports, and we release new product images for each operator images.
Nightly builds of operators are not considered here. In #147, I proposed to use the image pull policy "Always" for nightly builds. This has the advantage that for the development the same mechanism is used (the operator 1.0.0-nightly pulls the product image tagged with 1.0.0-nightly) and that the development can progress because always the latest version of the product image is used. The disadvantages of the image pull policy only apply to the nightly versions but not to the releases. The only downside is that the nightly versions behave differently to the releases.

2022-02-24 12:10 UTC, siegfriedweber commented on modules/contributor/pages/adr/drafts/ADRx-product_image_versioning.adoc
> +* Bad, because it increases the overhead of doing operator or image releases
Is this equivalent to "Bad because the operator must be released even if just the product image must be changed, e.g. due to a security update of the base image." in #147?

2022-02-25 08:48 UTC, teozkr commented on modules/contributor/pages/adr/drafts/ADRx-product_image_versioning.adoc
> +version is released.
True.

2022-02-25 09:00 UTC, teozkr commented on modules/contributor/pages/adr/drafts/ADRx-product_image_versioning.adoc
> +  * We could share the Docker layers to lessen this impact dramatically, but that would require rearchitecting our CI
So I need to do some experiments here to confirm, but from what I remember this isn't quite true. Each layer also has a bunch of metadata including a UUID, which would be different unless the base layers were explicitly reused (such as by `docker build`'s cache mechanism).

> Adding a new tag to an image does not alter its layer digests.

Correct, but that would require the build process to have any knowledge of the prior build.

> If the operator is changed but not the product image then there is only an additional tag pointing to an already existing product image. No storage space is wasted.
> If the product image is changed but not the operator then the operator is nevertheless recompiled containing the new version number. If I used dive correctly to inspect the image of the Superset operator then the three image layers at the top are regenerated. In this case 20 MB are wasted.

Yes, that would be the ideal case.

2022-02-25 09:07 UTC, teozkr commented on modules/contributor/pages/adr/drafts/ADRx-product_image_versioning.adoc
> +Each operator version hard-codes exactly one image version that it supports, and we release new product images for each operator images.
Nightlies are a good point to bring up... Personally, I'd rather tag nightlies with some form of build ID (commit hash?) than to start treating those image tags as mutable.

2022-02-25 09:07 UTC, teozkr commented on modules/contributor/pages/adr/drafts/ADRx-product_image_versioning.adoc
> +* Bad, because it increases the overhead of doing operator or image releases
Yes, or vice versa (product image must be released even if only the operator has any changes).

2022-02-25 09:10 UTC, teozkr commented on modules/contributor/pages/adr/drafts/ADRx-product_image_versioning.adoc
> +  * This means that it doesn't solve the original problem at all
People were taking it seriously in the meeting (and you mention wanting to rely on the same mechanism elsewhere in this very review), so I'd rather leave it where it's more discoverable...

2022-02-25 10:12 UTC, teozkr commented on modules/contributor/pages/adr/drafts/ADRx-product_image_versioning.adoc
> +express the range `^N.0.0` (`>=N.0.0 <N+1.0.0`), depending on the `-stackable$IMAGE_SEMVER_MAJOR` tag. This works
Tried to address this a bit more explicitly.

2022-02-28 08:45 UTC, teozkr commented on modules/contributor/pages/adr/drafts/ADRx-product_image_versioning.adoc
> +* Bad, because on-prem registry mirrors may not have whatever API or metadata we need to perform this resolution
I'm not sure how much it'd help to centralize that cache, since each operator basically only cares about its own ~one image.

2022-03-01 15:19 UTC, soenkeliebau commented on modules/contributor/pages/adr/drafts/ADRx-product_image_versioning.adoc
> +* Bad, because existing operators will switch which (minor-level) image version they deploy without user action
ah

2022-03-03 08:29 UTC, razvan commented
I think it's worth looking at what others are doing in this regard. Google's Spark operator for example, provides a clear version matrix: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator

2022-03-03 09:52 UTC, soenkeliebau commented on modules/contributor/pages/adr/drafts/ADRx-product_image_versioning.adoc
> +
Note to @soenkeliebau : 
Mention requirements around whether or not operators should be able to support multiple product versions and able to install versions that were not released when the operator was released.

2022-03-28 09:44 UTC, siegfriedweber requested changes

2022-03-28 09:44 UTC, siegfriedweber commented on modules/contributor/pages/adr/drafts/ADRx-product_image_versioning.adoc
> +|*2* - Synchronize image versions in lockstep with operator versions - Variant 1
```suggestion
|*2* - Synchronize image versions in lockstep with operator versions - Variant 2
```

2022-03-28 09:44 UTC, siegfriedweber commented on modules/contributor/pages/adr/drafts/ADRx-product_image_versioning.adoc
> +|*4* - Use SemVer for docker images, independently of operator version - Variant 1
```suggestion
|*4* - Use SemVer for docker images, independently of operator version - Variant 2
```

2022-04-07 10:38 UTC, teozkr commented
Looks reasonable to me. Might want to change title of one of them, and add the product image one to the nav toc.

2022-05-05 09:52 UTC, siegfriedweber requested changes

2022-05-05 09:52 UTC, siegfriedweber commented on modules/contributor/pages/adr/drafts/ADRx-operator_image_version_selection.adoc
> += ADRx: Product Image Versioning
The title of this document should be "ADRx: Operator image version selection". It currently contains only an outdated version of ADR18. So it would be better to just remove the entire file and restart from scratch when this topic comes up again.

There is only one noteworthy discussion we had in our meeting which should be written down somewhere: There must be a compatibility matrix for the operator and product versions. This matrix should probably contain at least the following states: "compatible" (which means tested and supported by Stackable), "unsupported" (which means there is no known technical restriction which prevents you from using it but it is either not tested or contains vulnerabilities), and "incompatible" (which means there were breaking changes and this combination will not work). This compatibility matrix should not be hard-coded into the operators because then a new release of an operator is required every time a new product version should be supported by this operator. Instead it should be read from a config map.

2022-05-05 09:52 UTC, siegfriedweber commented on modules/contributor/pages/adr/ADR018-product_image_versioning.adoc
> +==== Variant 1 - Git tags contains only the Stackable image version
```suggestion
==== Variant 1 - Git tags contain only the Stackable image version
```

2022-05-05 09:52 UTC, siegfriedweber commented on modules/contributor/pages/adr/ADR018-product_image_versioning.adoc
> +|2.9.0_stackable0.1.2
This entry is not necessary. But if it is kept then the Stackable versions must not differ.

2022-05-05 09:52 UTC, siegfriedweber commented on modules/contributor/pages/adr/ADR018-product_image_versioning.adoc
> +* it allows us to decouple operator version and image version to a high degree
```suggestion
The main reasons for picking this option were:

* it allows us to decouple operator version and image version to a high degree
```

The new line is necessary. Otherwise the list is not rendered as a list.

2022-05-05 09:52 UTC, siegfriedweber commented on modules/contributor/pages/adr/ADR018-product_image_versioning.adoc
> +NOTE: Image versions are only comparable when combined with the product version _0.1.0_ in kafka2.8.0_stackable0.1.0 and kafka2.9.0_stackable0.1.0 are two completely different versions _0.1.0_
This is hard to read. It should be split into two sentences.

2022-05-05 10:05 UTC, soenkeliebau commented on modules/contributor/pages/adr/ADR018-product_image_versioning.adoc
> +|2.9.0_stackable0.1.2
The 2 was a typo, good catch!

But as for whether or not it is neccesary, I included it to highlight the fact that 0.1.1 can be released for one Kafka version but not the other.

2022-05-05 10:10 UTC, soenkeliebau commented on modules/contributor/pages/adr/ADR018-product_image_versioning.adoc
> +NOTE: Image versions are only comparable when combined with the product version _0.1.0_ in kafka2.8.0_stackable0.1.0 and kafka2.9.0_stackable0.1.0 are two completely different versions _0.1.0_
done

2022-05-05 10:10 UTC, soenkeliebau commented on modules/contributor/pages/adr/ADR018-product_image_versioning.adoc
> +* it allows us to decouple operator version and image version to a high degree
done

2022-05-05 10:10 UTC, soenkeliebau commented on modules/contributor/pages/adr/ADR018-product_image_versioning.adoc
> +==== Variant 1 - Git tags contains only the Stackable image version
done

2022-05-05 10:49 UTC, siegfriedweber approved these changes
LGTM

2022-05-05 11:12 UTC, merged