Hackathon tutorial
stackabletech/documentation pull request #211
Opened 2022-06-10 12:33 UTC by Jimvin

Fixes to the tutorial as some of the resources used have been moved or modified.

2022-06-13 07:47 UTC, fhennig requested changes
Just one minor thing basically

2022-06-13 07:47 UTC, fhennig commented on modules/tutorials/pages/end-to-end_data_pipeline_example.adoc
> +helm install --repo https://repo.stackable.tech/repository/helm-dev nifi-operator nifi-operator --version=0.6.0-nightly
So this is nothing to fix, just a comment :D

2022-06-14 14:28 UTC, Jimvin commented on modules/tutorials/pages/end-to-end_data_pipeline_example.adoc
> +To deploy Kafka and NiFi we can now apply our cluster configuration. We'll also need to deploy ZooKeeper, since both Kafka and NiFi depend on it. Run the following command in the console to deploy an
Done!

2022-06-15 06:59 UTC, fhennig approved these changes
LGTM!

2022-06-15 06:59 UTC, merged