Role and role group documentation
stackabletech/documentation pull request #221
Opened 2022-06-23 13:08 UTC by fhennig

closes #191 

This adds a new concepts page to explain roles and role groups

2022-06-30 17:20 UTC, fhennig commented
it's not urgent

2022-07-01 17:46 UTC, maltesander requested changes
One minor error mistakes and some comments. LGTM otherwise!

2022-07-01 17:46 UTC, maltesander commented on modules/concepts/pages/roles-and-role-groups.adoc
> +Software - especially the distributed kind - often consists of multiple different process that work together to achieve their goal, Stackable calls these _roles_. The same kind of process is then oft
```suggestion
Software - especially the distributed kind - often consists of multiple different processes that work together to achieve their goal. Think of a client communicating with a server. Stackable calls these _roles_. The roles or processes are often replicated multiple times. These replicas can further be subdivided into _role groups_. Roles and role groups are defined in the resource manifest.
```

2022-07-01 17:46 UTC, maltesander commented on modules/concepts/pages/roles-and-role-groups.adoc
> +The use of roles and role groups is motivated by the need to configure differently *how* processes are configured and *where* they run.
```suggestion
The use of roles and role groups is required to control *how* processes are configured and *where* they run.
```

2022-07-01 17:46 UTC, maltesander commented on modules/concepts/pages/roles-and-role-groups.adoc
> +Role groups are motivated by the need to subdivide the replicas of a processes into groups as well, either to configure multiple groups differently or to schedule them differently. For example in a c
```suggestion
Role groups are motivated by the need to subdivide the replicas of a process into groups as well, either to configure or to schedule multiple groups differently. For example in a cluster spanning multiple physical locations, you may want to make sure half of your processes run in one location and half in the other.
```

2022-07-01 17:46 UTC, maltesander commented on modules/concepts/pages/roles-and-role-groups.adoc
> +A distributed software has multiple roles. Every role must be configured with at least one role group. Configuration can be specified at role level or at role group level, where the role group level
```suggestion
A distributed software consists of one or more roles. Every role must be configured with at least one role group. Configuration can be specified at role level or at role group level, where the role group level overrides the role level. Label selectors for scheduling and the number of replicas are specified on the role group, not role. The role group is the lowest level, so it makes sense to have to specify this there.
```

2022-07-01 17:46 UTC, maltesander commented on modules/concepts/pages/roles-and-role-groups.adoc
> +<1> The JournalNode role with only a single default role group. For the role group 3 replicas are specified, specifying a replica count is not optional.
This is not quite true. Replicas are optional and default to 1.
``` 
Replicas is the desired number of replicas of the given Template. These are replicas in the sense that they are instantiations of the same Template, but individual replicas also have a consistent identity. If unspecified, defaults to 1.
```

2022-07-04 10:51 UTC, maltesander approved these changes
LGTM.

2022-07-04 10:58 UTC, merged