added a note on PVC usage
stackabletech/documentation pull request #224
Opened 2022-06-30 08:59 UTC by adwk67

For some clusters (IONOS, Azure, AWS) PVC-usage for tests requires explicit node selection, whereas for others (K3S, KinD) this is taken into account. This note provides a short explanation.

2022-06-30 09:07 UTC, teozkr commented on modules/concepts/pages/pvc.adoc
> +This suggests that resources are automatically considered when pods are assigned to nodes, but it is not clear if the same is true for implicit dependencies, such as `PersistentVolumeClaim` usage. Th
Yes. The PVC is resolved to its corresponding PV, and the scheduling constraints of the PV are taken into account when scheduling the node.

2022-06-30 11:17 UTC, adwk67 commented on modules/concepts/pages/pvc.adoc
> +The only viable access mode is thus `ReadWriteOnce` (see above) which means that all test steps dependent on a `PersistentVolumeClaim` should be run on the same node, and this assignment should be ma
Changed as per suggestion

2022-06-30 11:17 UTC, adwk67 commented on modules/concepts/pages/pvc.adoc
> +This suggests that resources are automatically considered when pods are assigned to nodes, but it is not clear if the same is true for implicit dependencies, such as `PersistentVolumeClaim` usage. Th
Changed as per suggestion

2022-06-30 11:18 UTC, adwk67 commented on modules/concepts/pages/pvc.adoc
> +A `PersistentVolume` will usually be provisioned by the cluster administrator, who will take into account the type of storage that is required. This will include, for example, an appropriate sizing,
Changed as per suggestion

2022-06-30 11:19 UTC, adwk67 commented on modules/concepts/pages/pvc.adoc
> +For `PersistentVolumeClaim`-relevant tests in the Stackable operator repositories the backing `PersistentVolume` is usually omitted as this is an implementation/provisioning choice to made by the clu
Changed as per suggestion

2022-06-30 11:19 UTC, adwk67 commented on modules/concepts/pages/pvc.adoc
> +A `PersistentVolume` will usually be provisioned by the cluster administrator, who will take into account the type of storage that is required. This will include, for example, an appropriate sizing,
Changed as per suggestion

2022-06-30 15:47 UTC, adwk67 commented on modules/concepts/pages/pvc.adoc
> += `PersistentVolumeClaim` usage
Implemented as suggested.

2022-06-30 15:48 UTC, adwk67 commented on modules/concepts/pages/pvc.adoc
> +== Access modes and the `StorageClass`
Added links and an example.

2022-06-30 16:56 UTC, fhennig requested changes
At the end, can you add a "Further reading" section or similar, linking to the specific usage of PVCs in operators that use it? Airflow, Spark (and more?)

2022-06-30 16:56 UTC, fhennig commented on modules/concepts/pages/pvc.adoc
> +== Node selection
This section feels like it is missing a conclusion. Can we find out what to suggest to the user? Should they use labels and selectors to enforce scheduling of pods, or do they not need to do that?

2022-06-30 16:57 UTC, fhennig commented
Sorry for not submitting all this feedback at once!

2022-07-04 07:20 UTC, adwk67 commented on modules/concepts/pages/pvc.adoc
> +== Test considerations
Yes, I agree. I just wanted to note it somewhere rather than forget it. Shall we leave it here until we find a more obvious place? (maybe under the section for contributors?)

2022-07-04 08:53 UTC, fhennig commented on modules/concepts/pages/pvc.adoc
> +== Test considerations
Yes it's probably fine to leave it here for now

2022-07-04 09:14 UTC, adwk67 commented on modules/concepts/pages/pvc.adoc
> +== Node selection
I have added a short list of considerations in this section.

2022-07-04 09:36 UTC, adwk67 commented on modules/concepts/pages/pvc.adoc
> +== Node selection
...and some more links to online documentation and operator examples.

2022-07-20 07:09 UTC, soenkeliebau commented
waiting for @fhennig to get back

2022-07-25 08:54 UTC, fhennig requested changes

2022-07-25 08:54 UTC, fhennig commented on modules/concepts/pages/pvc.adoc
> +Not all https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes[access modes] are compatible with all storage classes. This https://docs.openshift.com/container-platform/4.8/stor
```suggestion
Not all storage classes support all https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes[access modes]. The supported access modes also depend on the Kubernetes implementation, see for example the compatiblity table https://docs.openshift.com/container-platform/4.8/storage/understanding-persistent-storage.html#pv-access-modes_understanding-persistent-storage[Supported access modes for PVs] in the OpenShift documentation. Other managed Kubernetes implementations will be similar, albeit with different default storage class names. The important point is that the default StorageClass only supports `ReadWriteOnce`, which limits access to the PersistentVolumeClaim to a single node. A strategy governing PersistentVolumeClaim resources will thus address the following:
```

2022-07-25 08:54 UTC, fhennig commented on modules/concepts/pages/pvc.adoc
> +Generally such constraints are unnecessary, as the scheduler will automatically do a reasonable placement (for example, spreading your Pods across nodes so as not place Pods on a node with insufficie
```suggestion
the scheduler will automatically do a reasonable placement (for example, spreading your Pods across nodes so as not place Pods on a node with insufficient free resources).
```

2022-07-25 08:54 UTC, fhennig commented on modules/concepts/pages/pvc.adoc
> +Generally such constraints are unnecessary, as the scheduler will automatically do a reasonable placement (for example, spreading your Pods across nodes so as not place Pods on a node with insufficie
I removed the "such constraints" bit, because it's referring to something that is not inside the quote, I found that confusing.

2022-07-25 08:54 UTC, fhennig commented on modules/concepts/pages/pvc.adoc
> +Not all https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes[access modes] are compatible with all storage classes. This https://docs.openshift.com/container-platform/4.8/stor
I tried to reformulate to get a better link text: https://developers.google.com/style/link-text

2022-07-25 08:54 UTC, fhennig commented on modules/concepts/pages/pvc.adoc
> +The Airflow operator can use a PersistentVolumeClaim for externally-loaded airflow jobs, known as Direct Acyclic Graphs (DAGs), as shown in this https://github.com/stackabletech/airflow-operator/blob
```suggestion
The xref:airflow::index.adoc[Airflow operator] can use a xref:airflow::usage.adoc#_via_persistentvolumeclaim[PersistentVolumeClaim for externally-loaded airflow jobs], known as Direct Acyclic Graphs (DAGs), as shown in this https://github.com/stackabletech/airflow-operator/blob/main/examples/simple-airflow-cluster-dags-pvc.yaml[example]. Airflow expects that all components (webserver, scheduler and workers) have access to the DAG folder, so the PersistentVolumeClaim either has to be accessible with the `ReadWriteMany` access mode or node selection should be declared to ensure all components run on the same node.
```

2022-07-25 08:54 UTC, fhennig commented on modules/concepts/pages/pvc.adoc
> +Users of the Spark-k8s operator have a variety of ways to manage SparkApplication dependencies, one of which is to mount resources on a PersistentVolumeClaim. An example is shown https://github.com/s
```suggestion
Users of the xref:spark-k8s::index.adoc[Spark-k8s operator] have a variety of ways to manage SparkApplication dependencies, one of which is to xref:spark-k8s::usage.adoc#_pyspark_externally_located_dataset_artifact_available_via_pvcvolume_mount[mount resources on a PersistentVolumeClaim]. An example is shown https://github.com/stackabletech/spark-k8s-operator/blob/main/examples/ny-tlc-report.yaml[here].
```

2022-07-25 09:12 UTC, fhennig approved these changes
LGTM

2022-07-25 09:17 UTC, adwk67 commented on modules/concepts/pages/pvc.adoc
> +The only viable access mode is thus `ReadWriteOnce` (see above) which means that all test steps dependent on a `PersistentVolumeClaim` should be run on the same node, and this assignment should be ma
Marking this as resolved as we have an upcoming meeting to discuss this (with a corresponding fine-tuning of these docs).

2022-07-25 09:18 UTC, merged