Opa concept docs
stackabletech/documentation pull request #230
Opened 2022-07-04 11:20 UTC by fhennig

WIP

2022-07-05 13:36 UTC, maltesander requested changes
Some minor hints (do not need to use them if you prefer the original)

2022-07-05 13:36 UTC, maltesander commented on modules/concepts/pages/opa.adoc
> +OPA is run by the xref:opa::index.adoc[Stackable OPA operator]. OPA is deployed with the OpaCluster resource, from which the operator creates a DaemonSet to run an OPA instance on every node of the c
```suggestion
OPA is run by the xref:opa::index.adoc[Stackable OPA operator]. OPA is deployed with the OpaCluster resource, from which the operator creates a DaemonSet to run an OPA instance on every node of the cluster. Because of this, every Pod making policy requests will always make the request locally, minimizing latency and network traffic.
```

2022-07-05 13:36 UTC, maltesander commented on modules/concepts/pages/opa.adoc
> +OPA by itself does not enforce a specific structure of Rego rules and the packages they are in, but the Stackable platform makes some assumptions. Whenever a product is connected to OPA (see <<_conne
Provide a product?

2022-07-05 13:36 UTC, maltesander commented on modules/concepts/pages/opa.adoc
> +The Rego rule policies are supplied as ConfigMaps. Multiple ConfigMaps can be used for multiple packages, for example one package for Druid authorization, one package for a Trino development instance
```suggestion
The Rego rule policies are supplied as ConfigMaps. Multiple ConfigMaps can be used for multiple packages, for example one package for Druid authorization, one package for a Trino development instance and one package for a Trino production instance. ConfigMaps were chosen as an easy to use method of supplying configuration files in a Kubernetes environment. The operator takes care of assembling the ConfigMaps into a policy bundle, every policy ConfigMap must contain a `opa.stackable.tech/bundle` label in order to be processed by the OPA operator.
```

2022-07-06 09:41 UTC, fhennig commented on modules/concepts/pages/opa.adoc
> +OPA by itself does not enforce a specific structure of Rego rules and the packages they are in, but the Stackable platform makes some assumptions. Whenever a product is connected to OPA (see <<_conne
What do you mean?

2022-07-06 09:58 UTC, maltesander approved these changes
LGTM.

2022-07-06 09:58 UTC, merged