Add concepts page on AuthenticationClass and TLS server verification
stackabletech/documentation pull request #323
Opened 2022-12-08 15:39 UTC by sbernauer

2022-12-12 16:48 UTC, maltesander requested changes
Just minor language things. LGTM otherwise!

2022-12-12 16:48 UTC, maltesander commented on modules/concepts/examples/authenticationclass-static-secret.yaml
> +  name: simple-trino-users-secret # <1>
Do we want do mention trino here?  Id prefer "simple-user-credentials" or something like that. 
(Should be adapted in authenticationclass-static-authenticationclass.yaml as well)

2022-12-12 16:48 UTC, maltesander commented on modules/concepts/pages/authenticationclass.adoc
> +Multiple operators use this CRD as a way to express the authentication of the product.
```suggestion
Multiple operators use this CRD as a way to express and configure the authentication methods of their respective product.
```

2022-12-12 16:48 UTC, maltesander commented on modules/concepts/pages/authenticationclass.adoc
> +* TLS
Nothing on TLS authentication?

2022-12-12 16:48 UTC, maltesander commented on modules/concepts/pages/authenticationclass.adoc
> +Here is an example that is tuned for an OpenLDAP LDAP server and is configured to read bind user credentials from a secret:
Not sure but strange to read with the double "LADP" :D
```suggestion
Here is an example that is tuned for an OpenLDAP server and is configured to read bind user credentials from a secret:
```

2022-12-12 16:48 UTC, maltesander commented on modules/concepts/pages/tls_server_verification.adoc
> +If the `tls` attribute is set to `null` (or is not specified) no TLS will be used for the connection.
```suggestion
If the `tls` attribute is set to `null` (or is not specified), no TLS will be used for the connection.
```

2022-12-12 16:48 UTC, maltesander commented on modules/concepts/pages/tls_server_verification.adoc
> +The parties participating at an TLS connection can be verified using certificates.
```suggestion
The parties participating via a TLS connection can be verified using certificates.
```

2022-12-12 16:48 UTC, maltesander commented on modules/concepts/pages/tls_server_verification.adoc
> +At the moment the following verification methods are supported
```suggestion
At the moment the following verification methods are supported:
```

2022-12-12 16:48 UTC, maltesander commented on modules/concepts/pages/tls_server_verification.adoc
> +So if you got provided with a ca cert but don't have access to the key you can still use this method.
```suggestion
So if you were provided with a ca cert but do not have access to the key you can still use this method.
```

2022-12-13 07:15 UTC, sbernauer commented on modules/concepts/examples/authenticationclass-static-secret.yaml
> +  name: simple-trino-users-secret # <1>
Agreed, copied it from somewhere else. 64ec2ae14eb7cfde42e79ceb68195f5c11cfadac

2022-12-13 07:30 UTC, sbernauer commented on modules/concepts/pages/authenticationclass.adoc
> +* TLS
I was lazy and did get things done ^^ f571e5d2b16a70aa2766f74e529531c5175c0da7

2022-12-13 08:34 UTC, maltesander approved these changes
LGTM.

2022-12-13 09:52 UTC, merged