concepts reorganized and new overview page
stackabletech/documentation pull request #325
Opened 2022-12-12 08:20 UTC by fhennig

I made this during the break week

2023-12-25 23:50 UTC, fhennig commented
Look here: https://deploy-preview-325--stackable-docs.netlify.app/home/nightly/concepts/

2023-12-27 08:30 UTC, sbernauer requested changes
Awesome. very nice!

2023-12-27 08:30 UTC, sbernauer commented on modules/concepts/images/operator_overview.drawio.svg
Nit: STS and CM are actually per role group, not role

2023-12-27 08:30 UTC, sbernauer commented on modules/concepts/pages/overview.adoc
> +To deploy a product instance, a product resource needs to be created in Kubernetes, this is usually done by passing a YAML manifest file to kubernetes with `kubectl apply -f`. The manifest file conta
```suggestion
To deploy a product instance, a product resource needs to be created in Kubernetes, this is usually done by passing a YAML manifest file to kubernetes with `kubectl apply -f <file.yaml>`. The manifest file contains the configuration of how the product should operate.
```

2023-12-27 08:30 UTC, sbernauer commented on modules/concepts/images/common_objects.drawio.svg
Can we please rename `LdapServer` to `Ldap configuration`? Technically AuthenticationClass would be correct, but that could be considered a implementation detail

2023-12-29 10:57 UTC, fhennig commented on modules/concepts/images/operator_overview.drawio.svg
As there are no role groups in the image at all, I'd just leave it like this. I think the general concept is clear, and that's what this illustration is for

2023-12-29 10:58 UTC, fhennig commented on modules/concepts/images/common_objects.drawio.svg
I fixed this one! Since S3Bucket is an actual object I turned the Ldap concfig into an AuthenticationClass

2024-01-02 08:35 UTC, sbernauer commented on modules/concepts/images/operator_overview.drawio.svg
Alright

2024-01-02 08:35 UTC, sbernauer approved these changes

2024-01-02 08:42 UTC, merged