Adds explanation of crate2nix and tilt based development workflow to the docs
stackabletech/documentation pull request #360
Opened 2023-02-12 14:21 UTC by soenkeliebau

For implementation PRs, see:
 - https://github.com/stackabletech/operator-templating/pull/212
 - https://github.com/stackabletech/hdfs-operator/pull/312

2023-02-13 08:26 UTC, nightkr commented on modules/contributor/pages/testing_on_kubernetes.adoc
> +Effectively this means, that when you have reached a state in your code that you would like to deploy to Kubernetes to look at more in depth, all you need to do is .. nothing - it has already been bu
```suggestion
Effectively this means, that when you have reached a state in your code that you would like to deploy to Kubernetes to look at more in depth, all you need to do is .. nothing - it has already been built, packaged and deployed in the background.
```

2023-02-13 08:26 UTC, nightkr commented on modules/contributor/pages/testing_on_kubernetes.adoc
> +----
At a minimum, you also need to add `extra-experimental-features = nix-command` to `/etc/nix/nix.conf`.

2023-02-13 10:26 UTC, siegfriedweber requested changes
This pull request should also be approved by non-NixOS users and people who have not used Nix before.

2023-02-13 10:26 UTC, siegfriedweber commented on modules/contributor/pages/testing_on_kubernetes.adoc
> +----
Correct but the setting is called `experimental-features` without `extra-`.

2023-02-13 10:26 UTC, siegfriedweber commented on modules/contributor/pages/testing_on_kubernetes.adoc
> +For more context on how to read this file please have a look at the https://docs.tilt.dev/api.html[Tiltfile API Reference], which is based on https://github.com/bazelbuild/starlark/blob/master/spec.m
**nit:** I would always link to a tag instead of a branch because these links tend to be more stable.

2023-02-13 10:42 UTC, nightkr commented on modules/contributor/pages/testing_on_kubernetes.adoc
> +----
Weird, that's what it's called in mine. Maybe it's a weird hack for the CLI flag that just happens to work then.

Agreed that `experimental-features` is better then.

2023-02-13 12:50 UTC, soenkeliebau commented on modules/contributor/pages/testing_on_kubernetes.adoc
> +For more context on how to read this file please have a look at the https://docs.tilt.dev/api.html[Tiltfile API Reference], which is based on https://github.com/bazelbuild/starlark/blob/master/spec.m
I went and had a look, they do not seem to have tags or branches..

2023-02-13 12:50 UTC, soenkeliebau commented on modules/contributor/pages/testing_on_kubernetes.adoc
> +----
done

2023-02-13 12:52 UTC, nightkr commented on modules/contributor/pages/testing_on_kubernetes.adoc
> +For more context on how to read this file please have a look at the https://docs.tilt.dev/api.html[Tiltfile API Reference], which is based on https://github.com/bazelbuild/starlark/blob/master/spec.m
Commit hashes, then. You can always press `y` to go to the commit hash URL of the page.

2023-02-13 14:04 UTC, soenkeliebau commented on modules/contributor/pages/testing_on_kubernetes.adoc
> +For more context on how to read this file please have a look at the https://docs.tilt.dev/api.html[Tiltfile API Reference], which is based on https://github.com/bazelbuild/starlark/blob/master/spec.m
done

2023-02-13 14:05 UTC, nightkr approved these changes
LGTM

2023-02-13 14:45 UTC, siegfriedweber submitted a review, later dismissed

2023-02-14 10:39 UTC, nightkr approved these changes

2023-02-14 11:47 UTC, sbernauer approved these changes
docs LGTM, worked well

2023-02-14 14:19 UTC, merged