Add ADR for systemd unit file handling decision.
stackabletech/documentation pull request #37
Opened 2021-01-07 10:33 UTC by soenkeliebau

I've investigated possibilities of where to place systemd unit files and drafted an ADR with what I think is the best way forward for now.

2021-01-07 10:52 UTC, lfrancke requested changes

2021-01-07 10:52 UTC, lfrancke commented on adr/ADR004-systemd_unit_file_location.adoc
> += Use English as Documentation Language
outdated

2021-01-07 10:52 UTC, lfrancke commented on adr/ADR004-systemd_unit_file_location.adoc
> +v1.0, 19.08.2020
outdated

2021-01-07 10:52 UTC, lfrancke commented on adr/ADR004-systemd_unit_file_location.adoc
> +* The risk of the community fragmenting into a german community and an international community is much lower
These two are leftovers I assume

2021-01-07 10:52 UTC, lfrancke commented on adr/ADR004-systemd_unit_file_location.adoc
> +* No versioning of unit files, as the current one will always be overwritten (this can be mitigated by keeping)
sentence ends too soon

2021-01-07 10:52 UTC, lfrancke commented on adr/ADR004-systemd_unit_file_location.adoc
> +* Bad, becausa it create the possibility of symlinks pointing at wrong unit files (if we version unit files)
```suggestion
* Bad, because it creates the possibility of symlinks pointing at wrong unit files (if we version unit files)
```

2021-01-07 10:59 UTC, lfrancke approved these changes

2021-01-07 11:02 UTC, lfrancke approved these changes

2021-01-12 08:46 UTC, merged

2021-01-13 08:38 UTC, ohessel commented
I would have also approved - looked good.