Updated ADR on operator reuse to reflect current state of affairs
stackabletech/documentation pull request #41
Opened 2021-01-15 15:14 UTC by soenkeliebau

2021-01-18 11:01 UTC, ohessel requested changes

2021-01-18 11:01 UTC, ohessel commented on adr/ADR8-decide_reuse_of_operators.adoc
> +** Config managmeent framework
** Config management framework

2021-01-18 12:49 UTC, soenkeliebau commented
Because I was stupid I had to revert parts of the commit, end result should now hopefully be correct and the confusing commits will disappear when we squash before merging.

2021-01-19 08:34 UTC, ohessel approved these changes

2021-01-19 08:38 UTC, merged