Document user overrides
stackabletech/documentation pull request #415
Opened 2023-06-13 14:19 UTC by sbernauer

2023-06-13 14:38 UTC, lfrancke requested changes

2023-06-13 14:38 UTC, lfrancke commented on modules/concepts/pages/user_overrides/config_overrides.adoc
> +WARNING: Overriding certain configurations can lead to faulty clusters. User overrides should only be used as a last resort!
```suggestion
WARNING: Overriding certain properties can lead to faulty clusters. User overrides should only be used as a last resort!
```

2023-06-13 14:38 UTC, lfrancke commented on modules/concepts/pages/user_overrides/env_overrides.adoc
> += Env overrides
```suggestion
= Environment variable overrides
```

2023-06-13 14:38 UTC, lfrancke commented on modules/concepts/pages/user_overrides/env_overrides.adoc
> +The env vars you can set dependents on the individual product.
```suggestion
The environment variables you can set depend on the specific product.
```

2023-06-13 14:38 UTC, lfrancke commented on modules/concepts/pages/user_overrides/index.adoc
> +WARNING: Overriding certain configurations can lead to faulty clusters. User overrides should only be used as a last resort!
```suggestion
WARNING: Overriding certain properties can lead to faulty clusters. Overrides should only be used as a last resort!
```

2023-06-14 06:49 UTC, lfrancke commented on modules/concepts/pages/user_overrides/index.adoc
> +WARNING: Overriding certain configurations can lead to faulty clusters. User overrides should only be used as a last resort!
I'm not sure if that is correct english.
@Jimvin can you help out?

2023-06-14 07:01 UTC, Jimvin commented on modules/concepts/pages/user_overrides/index.adoc
> +WARNING: Overriding certain configurations can lead to faulty clusters. User overrides should only be used as a last resort!
LGTM. It conveys the correct message, perhaps "Overrides should be used with caution!" might be better.

2023-06-14 07:19 UTC, fhennig commented
Great, thanks for documenting this! 

One thing: I'd like to have all of these in a single page `overrides.adoc` with 3 sub headings. You can still link to just Pod overrides by linking to the heading. I think they are all conceptually very similar and the pages are quite short.

2023-06-14 07:55 UTC, sbernauer commented
@fhennig was thinking about that as well in the beginning. I don't know if we will have more overrides in the future (e.g. for Services and pvcs). That was my main motivation of putting them in dedicated files. WDYT?

2023-06-14 08:16 UTC, lfrancke commented on modules/concepts/pages/user_overrides/index.adoc
> +WARNING: Overriding certain configurations can lead to faulty clusters. User overrides should only be used as a last resort!
Sorry, but...what looks good to you?

"configurations"? I'm not a native speaker so I might be wrong but it sounds...wrong to me.

2023-06-14 08:17 UTC, Jimvin commented on modules/concepts/pages/user_overrides/index.adoc
> +WARNING: Overriding certain configurations can lead to faulty clusters. User overrides should only be used as a last resort!
They are configuration properties, so either would work. I personally think properties makes more sense but I would be happy with either.

2023-06-15 09:54 UTC, fhennig commented
We talked over Slack and I convinced Sebastian of going with a single file

2023-06-15 10:27 UTC, sbernauer commented on modules/concepts/pages/user_overrides/index.adoc
> +WARNING: Overriding certain configurations can lead to faulty clusters. User overrides should only be used as a last resort!
Now we only have one warning at the top of the page left
It currently states `WARNING: Overriding certain configurations can lead to faulty clusters. Overrides should only be used as a last resort!`
I would say `configurations` includes config, env and pod the best, but happy to be overruled :) WDYT?
An alternative could also be `WARNING: Overriding certain aspects of your cluster setup can lead to faulty clusters. Overrides should only be used as a last resort and with care!`

2023-06-15 11:56 UTC, lfrancke submitted a review, later dismissed

2023-06-15 11:56 UTC, lfrancke commented on modules/concepts/pages/overrides.adoc
> +WARNING: Overriding certain configurations can lead to faulty clusters. Overrides should only be used as a last resort!
I still think it should be either `configuration properties` or just `properties`

`configurations` does not sound correct to me in this context.
The plural of `configuration` is used differently afaik.

2023-06-15 13:14 UTC, sbernauer commented on modules/concepts/pages/overrides.adoc
> +WARNING: Overriding certain configurations can lead to faulty clusters. Overrides should only be used as a last resort!
Alright, changing to `configuration properties`

2023-06-15 14:08 UTC, merged

2023-06-16 08:31 UTC, fhennig reviewed
Some ideas

2023-06-16 08:31 UTC, fhennig commented on modules/concepts/pages/overrides.adoc
> +The cluster definitions also supports overriding configuration aspects, either per role or per role group, where the more specific override (role group) has precedence over the less specific one (rol
I have a suggestion for an introduction to the whole topic:

"The Stackable Operators configure the products they are operating with sensible defaults, and required settings to enable connectivity and securty when enabled. Other important settings are usually exposed as settings in the resource definition. In some cases however, you might want to set certain settings that are not exposed, or override settings that the operator has set on the product.

The resource definitions of all products support overrides, specificially for the product configuration, environment variables, and the Pod spec the Operators generate."

I'd add this before the warning as an introduction to the topic

2023-06-16 08:31 UTC, fhennig commented on modules/concepts/pages/overrides.adoc
> +
For i.e. `.properties` files this is obvious, but I'm wondering how this works for XML. Maybe a quick example could be added?

2023-06-16 08:31 UTC, fhennig commented on modules/concepts/pages/overrides.adoc
> +All override property values must be strings.
Is this correct? I think I can set _any_ variable, but maybe not everything makes sense. But there's not technical limitation, right?

2023-06-16 08:31 UTC, fhennig commented on modules/concepts/pages/overrides.adoc
> +For a role or role group, at the same level of `config`, you can specify `podOverrides` for any of the attributes you can configure on a Pod.
"... These overriden settings will be added to the PodTemplate of the StatefulSet of the role group" (link to the roles-and-role-groups concept page)

2023-06-16 10:53 UTC, sbernauer commented on modules/concepts/pages/overrides.adoc
> +For a role or role group, at the same level of `config`, you can specify `podOverrides` for any of the attributes you can configure on a Pod.
It can also be daemonsets. Good question is how we want to handle jobs we write out, e.g. for Airflow and Superset.
Will link to the concept

2023-06-16 10:57 UTC, sbernauer commented on modules/concepts/pages/overrides.adoc
> +
Not sure if I did this right, as the example above is using xml :thinking:

2023-06-16 11:05 UTC, sbernauer commented
@fhennig created https://github.com/stackabletech/documentation/pull/416