Tutorial: Verify image signatures
stackabletech/documentation pull request #421
Opened 2023-07-17 10:36 UTC by dervoeti

2023-07-17 11:24 UTC, sbernauer commented on modules/tutorials/pages/enabling_verification_of_image_signatures.adoc
> +include::example$verify-signatures/kyverno-policy.yaml[]
Seems like you are missing a examples file ;)

2023-07-17 12:22 UTC, dervoeti commented on modules/tutorials/pages/enabling_verification_of_image_signatures.adoc
> +include::example$verify-signatures/kyverno-policy.yaml[]
Yep :man_facepalming: Forgot to add it. Fixed now.

2023-07-18 10:51 UTC, sbernauer reviewed
Text LGTM, but haven't had the time to test the policy yet

2023-07-19 10:15 UTC, adwk67 requested changes
Just some minor suggestions. Not tested yet.

2023-07-19 10:15 UTC, adwk67 commented on modules/tutorials/pages/enabling_verification_of_image_signatures.adoc
> +Image signing is a security measure that can help ensuring the authenticity and integrity of container images. Starting with SDP 23.7, all our operator images are signed https://docs.sigstore.dev/cos
```suggestion
Image signing is a security measure that helps ensure the authenticity and integrity of container images. Starting with SDP 23.7, all our operator images are signed https://docs.sigstore.dev/cosign/openid_signing/["keyless"] (signing of product images and Helm charts will follow). By verifying these signatures, cluster administrators can ensure that the operator images pulled from Stackable's container registry are authentic and have not been tampered with.
```

2023-07-19 10:15 UTC, adwk67 commented on modules/tutorials/pages/enabling_verification_of_image_signatures.adoc
> +Now that Kyverno is installed, we can create a policy that verifies that all operator images of SDP 23.7 releases are signed by Stackable's CI pipeline (Github Actions):
```suggestion
Now that Kyverno is installed, we can create a policy that verifies that all operator images that are part of the SDP 23.7 releases are signed by Stackable's CI pipeline (Github Actions):
```

2023-07-19 10:15 UTC, adwk67 commented on modules/tutorials/pages/enabling_verification_of_image_signatures.adoc
> +The policy will be applied to all namespaces in the cluster. It checks all newly created Pods that run any image matching the expression `docker.stackable.tech/*-operator:23.7.*` (all Stackable opera
```suggestion
The policy will be applied to all namespaces in the cluster. It checks all newly created Pods that run any image matching the expression `docker.stackable.tech/*-operator:23.7.*` (all Stackable operators version 23.7.*) and ensures that these images have been signed by a Stackable Github Action from the release 23.7 (`https://github.com/stackabletech/*-operator/.github/workflows/build.yml@refs/tags/23.7.*`). If the signature of an operator image is invalid or missing, the policy will deny the pod creation.
```

2023-07-19 10:15 UTC, adwk67 commented on modules/tutorials/pages/enabling_verification_of_image_signatures.adoc
> +If we would change the `subject` field in the policy to something like `https://github.com/test/*`, the policy will deny the creation of operator pods because the signature is not valid anymore.
```suggestion
If the `subject` field in the policy is changed to something like `https://github.com/test/*`, the policy will deny the creation of operator pods because the signature is no longer valid.
```

2023-07-19 10:27 UTC, adwk67 reviewed
Tested and works. Is there anyway to query the results or is the fact that pod-creation is not blocked all the feedback one gets? I see a lot of this in the logs, even thought the pods are created:

> "Event occurred" object="verify-image-signatures" fieldPath="" kind="ClusterPolicy" apiVersion="kyverno.io/v1" type="Warning" reason="PolicyViolation" message="ReplicaSet default/spark-k8s-operator-deployment-59b68f55bf: [autogen-verify-stackable-signatures] fail; missing digest for docker.stackable.tech/stackable/spark-k8s-operator:23.7.0"

This is probably the confirmation log:

> "Event occurred" object="verify-image-signatures" fieldPath="" kind="ClusterPolicy" apiVersion="kyverno.io/v1" type="Normal" reason="PolicyApplied" message="Deployment default/trino-operator-deployment: pass"

2023-07-19 15:39 UTC, dervoeti commented
Yeah the fact that pod-creation works is the "positive" feedback, I then edited the `issuer` field in the Kyverno policy to something invalid (like "https://github.com/invalid/*") and tried to install a 23.7 operator, which then failed ("negative" feedback). The error you see in the log seems to be a temporary one when starting the image, not 100% sure though.

2023-07-19 15:43 UTC, adwk67 commented
> Yeah the fact that pod-creation works is the "positive" feedback, I then edited the `issuer` field in the Kyverno policy to something invalid (like "[@invalid](https://github.com/invalid/)*") and tried to install a 23.7 operator, which then failed ("negative" feedback). The error you see in the log seems to be a temporary one when starting the image, not 100% sure though.

Thanks - that makes sense that it may be a startup issue! I'll approve this.

2023-07-19 15:43 UTC, adwk67 approved these changes

2023-07-19 16:28 UTC, merged