Added preliminary project documentation
stackabletech/documentation pull request #44
Opened 2021-02-03 17:03 UTC by ohessel

I hope I pictured everything correctly in consolidating the existing documents and documentation

2021-02-05 09:28 UTC, lfrancke requested changes

2021-02-05 09:28 UTC, lfrancke commented on README.adoc
> +The API-Server acts as a centralized storage for configuration files. It has the function to distribute the updated files and configurations or inform the other components about the current changes.
```suggestion
The API-Server acts as a centralized frontend for the clusters shared storage. It is the component through which all other components (i.e. Agents, Kubelet, Operators, ...) communicate.
```

It doesn't really deal in "files"

2021-02-05 09:28 UTC, lfrancke commented on README.adoc
> +For each application/Big Data Product there is exactly one special Operator defined. They must be registered to the API-Server for getting notified about upcoming configuration changes.
```suggestion
For each application/Big Data Product there is exactly one special Operator defined.
They watch for changes in their managed resources in the API-Server.
```

2021-02-05 09:28 UTC, lfrancke commented on README.adoc
> +This Operator is the expert of the application logic, how to roll out and update the Big Data Product (e.g. Kafka with the {base-repo}/kafka-operator[kafka-operator] and {base-repo}/zookeeper-operato
```suggestion
This Operator is the expert of the application logic, how to roll out and update the Big Data Product (e.g. Kafka with the {base-repo}/kafka-operator[kafka-operator] and {base-repo}/zookeeper-operator[zookeeper-operator]).
An Operator should implement and encompass all the knowledge a human operator would need when operating the service in question.
```

2021-02-05 09:28 UTC, lfrancke commented on README.adoc
> +Despite the Operator(s) the {base-repo}/agent[Agent(s)] are clones. But each Agent is running on its own VM. They must also be registered to the central API-Server, to get informed about updates.
I don't understand the first sentence. Could you explain what you mean?

2021-02-05 09:28 UTC, lfrancke commented on README.adoc
> +The client creates a YAML file for the API-Server, which defines the configuration for the Big Data Product (e.g. Kafka). There will be more possibilities to upload the file to the API-Server in futu
```suggestion
The client creates a YAML file for the API-Server, which defines the configuration for the Big Data Product (e.g. Kafka). The client then uses the usual Kubernetes tools (e.g. `kubectl` or any other Kubernetes client).
This means that the whole infrastructure will be described in code (Infrastructure-as-Code) and can be version controlled.
```

2021-02-05 09:28 UTC, lfrancke commented on README.adoc
> +The Operator(s), which are can run on the API-Server or on their own server, can be written in **Java** or in every other language you want. In the current implementation **Rust** is used for the Zoo
```suggestion
The Operator(s), which can run on the same server as the API-Server or on their own server, can be written in any programming language. We are using **Rust** to implement our Operators.
```

2021-02-05 09:28 UTC, lfrancke commented on README.adoc
> +Rust is a Programming language, which is focused on safety. It provides memory safety without a garbage collector, however the learning curve is steep.
```suggestion
Rust is a Programming language, which is focused on safety. It provides memory safety without a garbage collector.
```

No need to discourage anyone :)

2021-02-05 09:28 UTC, lfrancke commented on README.adoc
> +Finally the Agent(s) will provision the Big Data Product (e.g. setting up a Kafka) onto the node of its VM.
```suggestion
Finally, the Agent(s) will provision the Big Data Product (e.g. setting up a Kafka) onto the node of its VM.
```

2021-02-05 09:28 UTC, lfrancke commented on README.adoc
> +  - Availability of well supported libraries for necessary operations
```suggestion
  - Availability of well-supported libraries for necessary operations
```

2021-02-05 09:28 UTC, lfrancke commented on README.adoc
> +	- Debugging options
Could you replace tabs with spaces here?

2021-02-05 16:37 UTC, ohessel commented on README.adoc
> +The goal is to be able to declare full Data Platforms using this concept and go beyond pure low-level applications. This means that we want to be able to deploy a Kafka cluster for example. In future
I think it the better description for "Kafka Cluster" would be.

"a Kafka cluster together with Zookeeper, an authorization framework and a Spark cluster to consume a data stream"

2021-02-05 16:40 UTC, ohessel commented on README.adoc
> +This Operator is the expert of the application logic, how to roll out and update the Big Data Product (e.g. Kafka with the {base-repo}/kafka-operator[kafka-operator] and {base-repo}/zookeeper-operato
Coole Formulierung!

2021-02-05 16:42 UTC, ohessel commented on README.adoc
> +Despite the Operator(s) the {base-repo}/agent[Agent(s)] are clones. But each Agent is running on its own VM. They must also be registered to the central API-Server, to get informed about updates.
What I wanted to say is: 
The operator framework can be used to do the ground work, other than implementing the whole workflow/api by oneself.

2021-02-05 16:45 UTC, ohessel commented on README.adoc
> +The Operator(s), which are can run on the API-Server or on their own server, can be written in **Java** or in every other language you want. In the current implementation **Rust** is used for the Zoo
Same as the next one - there's rust, java is discontinued as operator-language (at least for now)

2021-02-05 16:47 UTC, ohessel commented on README.adoc
> +	- Debugging options
👍

2021-02-08 09:18 UTC, ohessel commented on README.adoc
> +Despite the Operator(s) the {base-repo}/agent[Agent(s)] are clones. But each Agent is running on its own VM. They must also be registered to the central API-Server, to get informed about updates.
I re-formulated the Agent and also Operator part, so the picture is clearer

2021-02-10 09:21 UTC, lfrancke approved these changes
Thank you!

2021-02-10 12:04 UTC, merged