Add some more information and examples to the image selection documentation
stackabletech/documentation pull request #445
Opened 2023-08-30 06:58 UTC by soenkeliebau

2023-08-30 07:38 UTC, fhennig requested changes
Hey, thank you for expanding this section, very nice! 

I have a few things, but mainly cosmetic. I also saw in a different part of the document a typo "wth" instead of "with", maybe you could fix that too while you're editing the document?

2023-08-30 07:38 UTC, fhennig commented on modules/concepts/pages/product_image_selection.adoc
> +Please see the warnings in xref:_custom_images for how to upgrade in this scenario.
This xref isn't working

2023-08-30 07:38 UTC, fhennig commented on modules/concepts/pages/product_image_selection.adoc
> +[WARNING]
I think this block of text could just be part of the text, without the WARNING box. What do you think?

2023-08-30 07:38 UTC, fhennig commented on modules/concepts/pages/product_image_selection.adoc
> +[CAUTION]
I think this can be a NOTE, instead of CAUTION, because it says that actually everything will be fine.

2023-08-30 07:38 UTC, fhennig commented on modules/concepts/pages/product_image_selection.adoc
> +What this means is, that for example the Stackable Operator for Apache HBase 23.4.0 will by default try to use images with the same stackable version.
```suggestion
What this means is, that for example the Stackable Operator for Apache HBase 23.4.0 will by default try to use _product_ images with the same Stackable version.
```

I think this sentence can be quite confusing, maybe you could also add an example version number for the product image? Also, how does the operator pick the product version, or is that version mandatory?

2023-08-30 07:38 UTC, fhennig commented on modules/concepts/pages/product_image_selection.adoc
> +### Planned Plattform Updates
```suggestion
### Planned platform updates
```

2023-08-30 07:38 UTC, fhennig commented on modules/concepts/pages/product_image_selection.adoc
> +## Common Scenarios
```suggestion
## Common scenarios
```

2023-08-30 07:38 UTC, fhennig commented on modules/concepts/pages/product_image_selection.adoc
> +#### Custom Images / Pinned Images
```suggestion
#### Custom images / pinned images
```

2023-08-30 07:38 UTC, fhennig commented on modules/concepts/pages/product_image_selection.adoc
> +### Quick Updates of Images
```suggestion
### Quick updates of images
```

2023-08-30 07:38 UTC, fhennig commented on modules/concepts/pages/product_image_selection.adoc
> +**Product Version** +
```suggestion
**Product version** +
```

2023-08-30 07:38 UTC, fhennig commented on modules/concepts/pages/product_image_selection.adoc
> +**Stackable Version** +
```suggestion
**Stackable version** +
```

2023-08-30 07:38 UTC, fhennig commented on modules/concepts/pages/product_image_selection.adoc
> +This is the version of the product which this image provides, so this could for example be Kafka 3.3.1
```suggestion
This is the version of the product which this image provides, so this could for example be Kafka 3.3.1.
```

2023-08-30 07:38 UTC, fhennig commented on modules/concepts/pages/product_image_selection.adoc
> +This is the version of the product which this image provides, so this could for example be Kafka 3.3.1
Maybe we could say "upstream version" as well, to clarify even more that this is not defined by us?

2023-08-30 07:38 UTC, fhennig commented on modules/concepts/pages/product_image_selection.adoc
> +For this scenario the Stackable Version can be set to the release line, without including the patchlevel indicator.
```suggestion
For this scenario the Stackable version can be set to the release line, without including the patch level indicator.
```

2023-08-30 07:38 UTC, fhennig commented on modules/concepts/pages/product_image_selection.adoc
> +Please see the warnings in xref:_custom_images for how to upgrade in this scenario.
You can also add anchors to section headers which you an then refer to like so:

```
== [[my-section]] My section with a long title

...

please read the <<my-section, section above>>.
```

2023-08-30 07:38 UTC, fhennig commented on modules/concepts/pages/product_image_selection.adoc
> +    productVersion: 3.3.1
maybe we could add more explanation here why the productVersion still needs to be specified. But this is optional

2023-08-30 20:22 UTC, soenkeliebau commented on modules/concepts/pages/product_image_selection.adoc
> +Please see the warnings in xref:_custom_images for how to upgrade in this scenario.
done

2023-08-30 20:24 UTC, soenkeliebau commented on modules/concepts/pages/product_image_selection.adoc
> +[CAUTION]
done

2023-08-30 20:28 UTC, soenkeliebau commented on modules/concepts/pages/product_image_selection.adoc
> +What this means is, that for example the Stackable Operator for Apache HBase 23.4.0 will by default try to use images with the same stackable version.
That sentence was actually followed by examples originally that I then removed for some reason..

2023-08-30 20:33 UTC, soenkeliebau commented on modules/concepts/pages/product_image_selection.adoc
> +    productVersion: 3.3.1
The explanation for that is already in the "custom images" section above. We could probably link to it from here if we wanted to ...

2023-08-31 07:32 UTC, fhennig approved these changes

2023-08-31 07:32 UTC, fhennig commented
Nice!

2023-09-11 06:46 UTC, sbernauer approved these changes
LGTM!

2023-09-11 06:46 UTC, sbernauer commented on modules/concepts/pages/product_image_selection.adoc
> +The following paragraphs explain  the available settings and how they work.
```suggestion
The following paragraphs explain the available settings and how they work.
```

2023-09-11 06:46 UTC, sbernauer commented on modules/concepts/pages/product_image_selection.adoc
> +** Tag clusters as "do not reconcile"
A link to https://docs.stackable.tech/home/stable/concepts/cluster_operations would be great

2023-09-11 06:52 UTC, soenkeliebau commented on modules/concepts/pages/product_image_selection.adoc
> +** Tag clusters as "do not reconcile"
Ah, right! I made a mental note of that when writing it and then immediately mentally burned the note :)

2023-09-11 06:57 UTC, soenkeliebau commented on modules/concepts/pages/product_image_selection.adoc
> +The following paragraphs explain  the available settings and how they work.
done

2023-09-11 06:57 UTC, soenkeliebau commented on modules/concepts/pages/product_image_selection.adoc
> +** Tag clusters as "do not reconcile"
done

2023-09-11 07:17 UTC, sbernauer approved these changes
Thanks!

2023-09-11 07:22 UTC, merged