docs: Add management and demo docs
stackabletech/documentation pull request #449
Opened 2023-09-12 14:50 UTC by Techassi

- Tracked by https://github.com/stackabletech/stackable-cockpit/issues/98
- Part of:
  - https://github.com/stackabletech/stackable-cockpit/pull/101
  - https://github.com/stackabletech/documentation-ui/pull/47

Supersedes #435

2023-09-20 09:36 UTC, fhennig commented on supplemental-ui/partials/navbar.hbs
>  <a class="navbar-sub-item" href="{{{ relativize "/home/stable/tutorials/end-to-end_data_pipeline_example.html" }}}">Tutorials</a>
I'd say we remove the Tutorials from the main menu. There isn't much there anyways, the demos are more useful for most users. And otherwise it's getting a bit too crowded in the menu I think

2023-09-20 10:42 UTC, Techassi commented on supplemental-ui/partials/navbar.hbs
>  <a class="navbar-sub-item" href="{{{ relativize "/home/stable/tutorials/end-to-end_data_pipeline_example.html" }}}">Tutorials</a>
Okay. I will remove the tutorials link.

2023-09-20 10:43 UTC, Techassi commented on modules/demos/nav.adoc
I wasn't quite sure if this is needed. But I think we can add links to all demos in here, right?

2023-09-20 10:46 UTC, Techassi commented on supplemental-ui/partials/navbar.hbs
>  <a class="navbar-sub-item" href="{{{ relativize "/home/stable/tutorials/end-to-end_data_pipeline_example.html" }}}">Tutorials</a>
Updated in f484afd

2023-09-20 12:05 UTC, fhennig commented on modules/demos/nav.adoc
yes that sounds good

2023-09-20 12:45 UTC, Techassi commented on modules/demos/nav.adoc
Added in 123a71f

2023-09-22 09:31 UTC, fhennig requested changes

2023-09-22 09:31 UTC, fhennig commented on local-antora-playbook.yml
>          - docs/0.6
```suggestion
```

2023-09-22 09:31 UTC, fhennig commented on local-antora-playbook.yml
>          - docs/0.4
```suggestion
```

2023-09-22 09:31 UTC, fhennig commented on modules/ROOT/pages/index.adoc
> +xref:home:airflow:index.adoc[Read more]
should simply be xref:airflow:index...

2023-09-22 09:31 UTC, fhennig commented on modules/ROOT/pages/index.adoc
> +xref:home:airflow:index.adoc[Read more]
same in the other links below

2023-09-22 09:31 UTC, fhennig commented on modules/ROOT/pages/release_notes.adoc
> +* xref:home:hive:index.adoc[] (0.6.0)
we are already in the home component, no need to include that in the xref

2023-09-22 10:02 UTC, Techassi commented on modules/ROOT/pages/release_notes.adoc
> +* xref:home:hive:index.adoc[] (0.6.0)
Changed in 8caa375

2023-09-22 10:02 UTC, Techassi commented on modules/ROOT/pages/index.adoc
> +xref:home:airflow:index.adoc[Read more]
Changed in 8caa375

2023-09-22 10:04 UTC, fhennig approved these changes

2023-09-22 10:10 UTC, merged