Add concepts page on Pod disruptions
stackabletech/documentation pull request #454
Opened 2023-09-19 13:46 UTC by sbernauer

2023-09-20 08:41 UTC, fhennig commented
an you explicitly define a section "proposed solution"? as a heading in there somewhere

2023-09-22 11:25 UTC, adwk67 requested changes
Mainly minor things.

2023-09-22 11:25 UTC, adwk67 commented on modules/concepts/pages/operations/pod_disruptions.adoc
> +1. Wether PDBs are written at all
```suggestion
1. Whether PDBs are written at all
```

2023-09-22 11:25 UTC, adwk67 commented on modules/concepts/pages/operations/pod_disruptions.adoc
> +In case you are not satisfied with the PDBs that are written by the operators, you can deploy you own ones.
```suggestion
In case you are not satisfied with the PDBs that are written by the operators, you can deploy your own.
```

2023-09-22 11:25 UTC, adwk67 commented on modules/concepts/pages/operations/pod_disruptions.adoc
> +IMPORTANT: It is important to disable the PDBs created by the operators as described above before creating your own PDBs, as this is a https://github.com/kubernetes/kubernetes/issues/75957[limitation
>  to disable the PDBs created by the operators

Maybe make it clear how this is done: by deleting the PodDisruptionBudget resources, or by disabling `podDisruptionBudget` for each role?

2023-09-22 11:25 UTC, adwk67 commented on modules/concepts/pages/operations/pod_disruptions.adoc
> +This PDB allows only on Pod out of all the Namenodes and Journalnodes to be down at a time.
```suggestion
This PDB allows only one Pod out of all the Namenodes and Journalnodes to be down at one time.
```

2023-09-22 14:15 UTC, sbernauer commented on modules/concepts/pages/operations/pod_disruptions.adoc
> +Please keep in mind, that this only affects planned (voluntary) downtime of Pods - multiple simulations Kubernetes node crashes can always occur!
I was trying to argue that two k8s node crashes can happen at the same time, so even if you have a HA setup of 2 Pods, both of them can be down at the same time.
Changed to "unplanned Kubernetes node crashes can always occur."

2023-09-22 14:17 UTC, sbernauer commented on modules/concepts/pages/operations/pod_disruptions.adoc
> +IMPORTANT: It is important to disable the PDBs created by the operators as described above before creating your own PDBs, as this is a https://github.com/kubernetes/kubernetes/issues/75957[limitation
You write `spec.nameNodes.roleConfig.podDisruptionBudget.enabled: false` and our operators will automatcially clean up the PDBs with the normal orphaned resources mechanism

2023-09-22 14:18 UTC, sbernauer commented on modules/concepts/pages/operations/pod_disruptions.adoc
> +IMPORTANT: It is important to disable the PDBs created by the operators as described above before creating your own PDBs, as this is a https://github.com/kubernetes/kubernetes/issues/75957[limitation
Changed to "It is important to disable the PDBs creating of the Stackable operators as described above before creating your own PDBs"

2023-09-22 14:57 UTC, adwk67 commented on modules/concepts/pages/operations/pod_disruptions.adoc
> +Please keep in mind, that this only affects planned (voluntary) downtime of Pods - multiple simulations Kubernetes node crashes can always occur!
Great, thanks!

2023-09-22 15:06 UTC, adwk67 commented on modules/concepts/pages/operations/pod_disruptions.adoc
> +IMPORTANT: It is important to disable the PDBs created by the operators as described above before creating your own PDBs, as this is a https://github.com/kubernetes/kubernetes/issues/75957[limitation
Thanks!

2023-09-22 15:15 UTC, adwk67 submitted a review, later dismissed
Nice - LGTM!

2023-09-25 12:56 UTC, adwk67 requested changes
Thank you for this: it's really helpful (for me at least!) to have all of this in one place.

2023-09-25 12:56 UTC, adwk67 commented on modules/concepts/pages/operations/index.adoc
> +This section of the documentation is intended for the operations teams, that maintain and take care of a Stackable Data Platform installation.
```suggestion
This section of the documentation is intended for the operations teams that maintain a Stackable Data Platform installation.
```

2023-09-25 12:56 UTC, adwk67 commented on modules/concepts/pages/operations/index.adoc
> +It provides you with the needed details to operate it in production.
```suggestion
It provides you with the necessary details to operate it in a production environment.
```

2023-09-25 12:56 UTC, adwk67 commented on modules/concepts/pages/operations/index.adoc
> +Make sure to go throw the following checklist to make sure you achieve the maximum level of availability for your services.
```suggestion
Make sure to go through the following checklist to achieve the maximum level of availability for your services.
```

2023-09-25 12:56 UTC, adwk67 commented on modules/concepts/pages/operations/index.adoc
> +   configure it for you. You only need to take sure that you deploy a sufficient number of replicas. Please note, that
```suggestion
   configure it for you. You only need to make sure that you deploy a sufficient number of replicas. Please note that
```

2023-09-25 12:56 UTC, adwk67 commented on modules/concepts/pages/operations/index.adoc
> +   within the Pod. The flow is, that Kubernetes wants to shut down the Pod and calls a hook into the Pod, which in turn
```suggestion
   within the Pod. The flow is as follows: Kubernetes wants to shut down the Pod and calls a hook into the Pod, which in turn
```

2023-09-25 12:56 UTC, adwk67 commented on modules/concepts/pages/operations/index.adoc
> +   interacts with the product, telling it to gracefully shut down. The final deletion of the Pod is than blocked until
```suggestion
   interacts with the product, telling it to gracefully shut down. The final deletion of the Pod is then blocked until
```

2023-09-25 12:56 UTC, adwk67 commented on modules/concepts/pages/operations/index.adoc
> +   the product has successfully migrated running workloads off of the Pod that get's shut down. Details of the actual graceful shutdown mechanism is described in the actual operator documentation.
```suggestion
   the product has successfully migrated running workloads away from the Pod that is to be shut down. Details covering the graceful shutdown mechanism are described in the actual operator documentation.
```

2023-09-25 12:56 UTC, adwk67 commented on modules/concepts/pages/operations/index.adoc
> +WARNING: Graceful shutdown is not implemented for all products yet. Please check the documentation on the product operator to see if it is supported for that specific product (such as e.g. xref:trino
```suggestion
WARNING: Graceful shutdown is not implemented for all products yet. Please check the documentation specific to the product operator to see if it is supported (such as e.g. xref:trino:usage_guide/operations/graceful-shutdown.adoc[the documentation for Trino].
```

2023-09-25 12:56 UTC, adwk67 commented on modules/concepts/pages/operations/index.adoc
> +4. Spread workload across multiple Kubernetes nodes, racks, datacenter rooms or datacenters to guaranteed availability
```suggestion
4. Spread workload across multiple Kubernetes nodes, racks, datacenter rooms or datacenters to guarantee availability
```

2023-09-25 12:56 UTC, adwk67 commented on modules/concepts/pages/operations/index.adoc
> +2. Prevent any changed to your deployed product using `reconcilePaused` as described in xref:operations/cluster_operations.adoc[].
```suggestion
2. Prevent any changes to your deployed product using `reconcilePaused` as described in xref:operations/cluster_operations.adoc[].
```

2023-09-25 12:56 UTC, adwk67 commented on modules/concepts/pages/operations/index.adoc
> +2. You can not only use xref:operations/pod_placement.adoc[] to achieve more resilience, but also co-locate products
```suggestion
2. You can not only use xref:operations/pod_placement.adoc[] to achieve more resilience, but also to co-locate products
```

2023-09-25 12:56 UTC, adwk67 commented on modules/concepts/pages/operations/index.adoc
> +   you are not satisfied of the automatically created affinities you can use ref:operations/pod_placement.adoc[] to
```suggestion
   you are not satisfied with the automatically created affinities you can use ref:operations/pod_placement.adoc[] to
```

2023-09-25 12:56 UTC, adwk67 commented on modules/concepts/pages/operations/index.adoc
> +   16 cores and 64 GB, as you could allocated nearly 100% of this node resources to your Spark executors or Trino workers.
```suggestion
   16 cores and 64 GB, as you could allocate nearly 100% of these node resources to your Spark executors or Trino workers.
```

2023-09-25 12:56 UTC, adwk67 commented on modules/concepts/pages/operations/index.adoc
> +   you Kubernetes nodes and use xref:overrides.adoc#pod-overrides[podOverrides] to add a `toleration` for the taint.
```suggestion
   your Kubernetes nodes and use xref:overrides.adoc#pod-overrides[podOverrides] to add a `toleration` for the taint.
```

2023-09-25 12:56 UTC, adwk67 commented on modules/concepts/pages/operations/pod_disruptions.adoc
> +IMPORTANT: It is important to disable the PDBs creating of the Stackable operators as described above before creating your own PDBs, as this is a https://github.com/kubernetes/kubernetes/issues/75957
```suggestion
IMPORTANT: It is important to disable the PDBs created by the Stackable operators as described above before creating your own PDBs, as this is a https://github.com/kubernetes/kubernetes/issues/75957[limitation of Kubernetes].
```

2023-09-25 13:02 UTC, adwk67 approved these changes

2023-09-25 13:03 UTC, merged