concepts: Document caveats with HPAs and PDBs
stackabletech/documentation pull request #461
Opened 2023-09-27 14:39 UTC by sbernauer

2023-09-29 10:07 UTC, maltesander requested changes
I find the pod disruption part very hard to read / understand. I try to come up with an alternative later.

2023-09-29 10:07 UTC, maltesander commented on modules/concepts/pages/operations/pod_disruptions.adoc
> +In case their are no replicas defined on a rolegroup, one Pod will be assumed for this rolegroup, as the created Kubernetes objects
```suggestion
In case there are no replicas defined on a rolegroup, one Pod will be assumed for this rolegroup, as the created Kubernetes objects
```

2023-09-29 10:07 UTC, maltesander commented on modules/concepts/pages/operations/pod_disruptions.adoc
> +can change dynamically. In this case the operators might falsely assume that rolegroups have less Pods than they actually have. This is a pessimistic approach,
```suggestion
can change dynamically. In this case the operators might falsely assume that rolegroups have fewer Pods than they actually have. This is a pessimistic approach,
```

2023-10-05 08:43 UTC, fhennig submitted a review, later dismissed

2023-10-05 12:40 UTC, maltesander requested changes

2023-10-05 12:40 UTC, maltesander commented on modules/concepts/pages/operations/pod_disruptions.adoc
> +more Pods *could* have been allowed to be unavailable, so rolling re-deployments can take a bit longer than needed.
Tried to rephrase a little and use less "we" and "you" (no strong opinion here).
I think performance does not really fit in here or probably deserves its own section?
```suggestion
In general, product roles are split into the following two categories, which serve as guidelines for the default values we apply:

=== Multiple replicas to increase availability

For these roles (e.g. ZooKeeper servers, HDFS journal + namenodes or HBase masters), only a single Pod is allowed to be unavailable. For example, imagine a cluster with 7 ZooKeeper servers, where 4 servers are required to form a quorum and healthy ensemble. By allowing 2 servers to be unavailable, there is no single point of failure (as there are at least 5 servers available). But there is only a single spare server left. The reason to choose 7 instead of e.g. 5 ZooKeeper servers might be, that there are always at least 2 spare servers. Increasing the number of allowed disruptions and increasing the number of replicas is not improving the general availability.

=== Multiple replicas to increase performance

For these roles (e.g. HDFS datanodes, HBase regionservers or Trino workers), more than a single Pod is allowed to be unavailable. Otherwise, rolling re-deployments may take very long.

IMPORTANT: The operators calculate the number of Pods for a given role by adding the number of replicas of every rolegroup that is part of that role.

In case there are no replicas defined on a rolegroup, one Pod will be assumed for this rolegroup, as the created Kubernetes objects (StatefulSets or Deployments) will default to a single replica as well. However, in case there are https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/[HorizontalPodAutoscaler] in place, the number of replicas of a rolegroup can change dynamically. In this case the operators might falsely assume that rolegroups have fewer Pods than they actually have. This is a pessimistic approach, as the number of allowed disruptions normally stays the same or even increases when the number of Pods increases. This should be safe, but in some cases more Pods *could* have been allowed to be unavailable which may increase the duration of rolling re-deployments.
```

2023-10-06 09:27 UTC, maltesander commented on modules/concepts/pages/operations/index.adoc
> +   Later platform versions will support autoscaling natively with sensible defaults and will deploy HorizontalPodAutoscaler objects for you.
If you decided it together im fine with it :)

2023-10-06 10:41 UTC, Techassi approved these changes

2023-10-06 11:33 UTC, maltesander approved these changes
LGTM!

2023-10-06 11:34 UTC, merged