WIP
stackabletech/documentation pull request #474
Opened 2023-10-19 11:00 UTC by fhennig

2023-10-19 12:49 UTC, Techassi requested changes
Some minor nits.

2023-10-19 12:49 UTC, Techassi commented on modules/ROOT/pages/policies.adoc
>  Customers are expected to upgrade their SDP environment to the most current supported patch/micro (`23.4.z`) version.
I would just call it patch version. The SemVer spec also uses the term `patch`.

2023-10-19 12:49 UTC, Techassi commented on modules/ROOT/pages/policies.adoc
> +Skipping SDP releases while upgrading is not currently supported.
```suggestion
Skipping SDP releases while upgrading is currently not supported.
```

2023-10-19 12:49 UTC, Techassi commented on supplemental-ui/partials/navbar.hbs
> +    Product Information
Maybe a better term would be `Policies and Licenses`. I would also suggest to move `Releases Notes` to the platform menu.

2023-10-19 14:21 UTC, fhennig commented on modules/ROOT/pages/policies.adoc
>  Customers are expected to upgrade their SDP environment to the most current supported patch/micro (`23.4.z`) version.
Earlier in the document it is mentioned that CalVer calls this part of the version the "micro" bit: https://calver.org/

That's why patch and micro are mentioned

2023-10-19 14:27 UTC, fhennig commented on supplemental-ui/partials/navbar.hbs
> +    Product Information
Thanks for the suggestion, I like it and did it.

2023-10-20 06:53 UTC, Techassi commented on modules/ROOT/pages/policies.adoc
>  Customers are expected to upgrade their SDP environment to the most current supported patch/micro (`23.4.z`) version.
Ah alright, then it's fine I guess.

2023-10-20 07:03 UTC, Techassi requested changes
Final nitpick.

2023-10-20 07:03 UTC, Techassi commented on modules/ROOT/pages/policies.adoc
> +We support an SDP release for a specific time after its release.
```suggestion
We support a SDP release for a specific amount of time after its initial release.
```

I'm not quite sure if `a` or `an` is correct here. Technically `a` is correct, but sounds a little funny in context.

2023-10-20 08:23 UTC, fhennig commented on modules/ROOT/pages/policies.adoc
> +We support an SDP release for a specific time after its release.
it's about the _sound_ so it'd be "an" here because it's "an _es dee pee_ release". But I like the other stuff!

2023-10-20 08:33 UTC, Techassi commented on modules/ROOT/pages/policies.adoc
> +We support an SDP release for a specific time after its release.
Yeah, I know. That's why I was a little unsure.

2023-10-20 08:33 UTC, Techassi approved these changes

2023-10-20 08:38 UTC, merged