Document restarts
stackabletech/documentation pull request #478
Opened 2023-11-01 11:28 UTC by razvan

Fixes https://github.com/stackabletech/documentation/issues/469

2023-11-01 14:47 UTC, nightkr commented on modules/concepts/pages/operations/cluster_operations.adoc
> +Sometimes you want to restart all `Pods` of stack and not just individual roles. This can be achieved in a similar manner by using labels instead of `StatefulSet` names. Continuing with the example a
For clarity we might want to use a different stacklet name here, to avoid it getting confused with Airflow-the-product or Airflow-the-operator.

2023-11-01 14:47 UTC, nightkr commented on modules/concepts/pages/operations/cluster_operations.adoc
> +❯ kubectl rollout status statefulset --selector app.kubernetes.io/instance=airflow
Same here.

2023-11-01 14:47 UTC, nightkr commented on modules/concepts/pages/operations/cluster_operations.adoc
> +Here we used the label `app.kubernetes.io/instance=airflow` to select all Pods that belong to a specific Airflow stack. This label is created by the operator and `airflow` is the name of the Airflow
```suggestion
Here we used the label `app.kubernetes.io/instance=airflow` to select all Pods that belong to a specific Airflow stacklet. This label is created by the operator and `airflow` is the name of the Airflow stacklet as specified in the custom resource. You can add more labels to make finer grained restarts.
```

2023-11-01 14:47 UTC, nightkr commented on modules/concepts/pages/operations/cluster_operations.adoc
> +NOTE: When using Airflow's https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/executor/kubernetes.html[Kubernetes executor], `worker` Pods are created dynamically by DAGs when needed
```suggestion
NOTE: When using Airflow's https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/executor/kubernetes.html[Kubernetes executor], `worker` Pods are created dynamically by DAGs when needed, in this case it is generally not necessary to restart them.
```

2023-11-01 14:47 UTC, nightkr commented on modules/concepts/pages/operations/cluster_operations.adoc
> +The Commons Operator of the Stackable Platform might restart Pods automatically, for example to ensure that security certificates are up-to-date. For details, see the xref:commons-operator:index.adoc
```suggestion
The Commons Operator of the Stackable Platform may restart Pods automatically, for purposes such as ensuring that security certificates are up-to-date. For details, see the xref:commons-operator:index.adoc[Commons Operator documentation].
```

2023-11-01 14:47 UTC, nightkr commented on modules/concepts/pages/operations/cluster_operations.adoc
> +NOTE: When using Airflow's https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/executor/kubernetes.html[Kubernetes executor], `worker` Pods are created dynamically by DAGs when needed
It feels slightly weird to call out Airflow specifically in this kind of "generic" documentation, but at the same time I can see why when it's the example product used throughout... Would it make sense to use a more "vanilla" product as our example here?

2023-11-01 14:57 UTC, fhennig commented on modules/concepts/pages/operations/cluster_operations.adoc
> +Most operators create `StatefulSet` objects for the products they manage and Kubernetes offers a rollout mechanism to restart them. You can use `kubectl rollout restart statefulset` to restart a Stat
yes, just CamelCase for objects like StatefulSet without code style please!

2023-11-01 14:58 UTC, fhennig commented on modules/concepts/pages/operations/cluster_operations.adoc
> +Sometimes you want to restart all `Pods` of stack and not just individual roles. This can be achieved in a similar manner by using labels instead of `StatefulSet` names. Continuing with the example a
A bit of topic, but: I think we need a page to define stacklet, because it isn't defined anywere atm

2023-11-01 15:48 UTC, razvan commented on modules/concepts/pages/operations/cluster_operations.adoc
> +NOTE: When using Airflow's https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/executor/kubernetes.html[Kubernetes executor], `worker` Pods are created dynamically by DAGs when needed
I agree this is very Airflow specific. I'm also fine with deleting this paragraph.

2023-11-01 15:48 UTC, nightkr commented on modules/concepts/pages/operations/cluster_operations.adoc
> +NOTE: When using Airflow's https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/executor/kubernetes.html[Kubernetes executor], `worker` Pods are created dynamically by DAGs when needed
I think something like Kafka or ZooKeeper would be a good example. Single role, no batch jobs, no special caveats.

2023-11-01 16:00 UTC, razvan commented on modules/concepts/pages/operations/cluster_operations.adoc
> +Most operators create `StatefulSet` objects for the products they manage and Kubernetes offers a rollout mechanism to restart them. You can use `kubectl rollout restart statefulset` to restart a Stat
Done https://github.com/stackabletech/documentation/pull/478/commits/c7942e9fb5fe102b0727dc5bbe79c08091569832

2023-11-01 16:29 UTC, razvan commented on modules/concepts/pages/operations/cluster_operations.adoc
> +Sometimes you want to restart all `Pods` of stack and not just individual roles. This can be achieved in a similar manner by using labels instead of `StatefulSet` names. Continuing with the example a
Renamed stacklet to `myairflow` to avoid some confusion: https://github.com/stackabletech/documentation/pull/478/commits/7149e7d23b430ab7c64c52dd3edaf6ea0ec6aa8f

2023-11-01 16:32 UTC, razvan commented on modules/concepts/pages/operations/cluster_operations.adoc
> +NOTE: When using Airflow's https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/executor/kubernetes.html[Kubernetes executor], `worker` Pods are created dynamically by DAGs when needed
But I think having multiple roles to watch out for is quite relevant in this case. Users might just want/need to start workers for example, and such an example raises awareness that they don't always have to do full restarts.

2023-11-01 16:33 UTC, razvan commented on modules/concepts/pages/operations/cluster_operations.adoc
> +For example, an Airflow stack will have three ServiceSets created for it: `scheduler`, `webserver` and `worker`. So given the following stateful sets deployed for an Airflow stacklet:
Done here https://github.com/stackabletech/documentation/pull/478/commits/6b2d8d65e301228df0d61be53c06ae6204dcb195

2023-11-01 16:48 UTC, razvan commented on modules/concepts/pages/operations/cluster_operations.adoc
> +Sometimes you want to restart all `Pods` of stack and not just individual roles. This can be achieved in a similar manner by using labels instead of `StatefulSet` names. Continuing with the example a
> A bit of topic, but: I think we need a page to define stacklet, because it isn't defined anywere atm

Like this? https://github.com/stackabletech/documentation/pull/479

2023-11-01 16:53 UTC, nightkr commented on modules/concepts/pages/operations/cluster_operations.adoc
> +NOTE: When using Airflow's https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/executor/kubernetes.html[Kubernetes executor], `worker` Pods are created dynamically by DAGs when needed
That's fair… how about HDFS?

2023-11-01 17:18 UTC, razvan commented on modules/concepts/pages/operations/cluster_operations.adoc
> +NOTE: When using Airflow's https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/executor/kubernetes.html[Kubernetes executor], `worker` Pods are created dynamically by DAGs when needed
Switched to HDFS: https://github.com/stackabletech/documentation/pull/478/commits/c5179e3973b73d8dc67b0416f37154b6b24d0601

2023-11-02 10:36 UTC, sbernauer requested changes
Thanks a  lot for documenting this! LGTM otherwise

2023-11-02 10:36 UTC, sbernauer commented on modules/concepts/pages/operations/cluster_operations.adoc
> +❯ kubectl get sts -l app.kubernetes.io/instance=dumbo
To be consistent :)
```suggestion
❯ kubectl get statefulset -l app.kubernetes.io/instance=dumbo
```

2023-11-02 10:36 UTC, sbernauer commented on modules/concepts/pages/operations/cluster_operations.adoc
> +To restart the HDFS data node Pods, run:
```suggestion
To restart the HDFS DataNode Pods, run:
```

2023-11-02 10:36 UTC, sbernauer commented on modules/concepts/pages/operations/cluster_operations.adoc
> +The Commons Operator of the Stackable Platform may restart Pods automatically, for purposes such as ensuring that security certificates are up-to-date. For details, see the xref:commons-operator:inde
```suggestion
The Commons Operator of the Stackable Platform may restart Pods automatically, for purposes such as ensuring that TLS certificates are up-to-date. For details, see the xref:commons-operator:index.adoc[Commons Operator documentation].
```

2023-11-02 11:38 UTC, sbernauer approved these changes

2023-11-02 11:42 UTC, merged