Added a _getting started_ guide to set up a blank environment that can be used to deploy services.
stackabletech/documentation pull request #50
Opened 2021-03-01 11:19 UTC by soenkeliebau

2021-03-01 12:26 UTC, ohessel commented on README.adoc
> +image::images/quickstart_architecture.png[]
Image is not part of the PR - please add.

2021-03-01 14:19 UTC, backstreetkiwi commented on README.adoc
> +image::images/quickstart_architecture.png[]
I'll review this by using the guide to work on Issue https://github.com/stackabletech/t2/issues/11

2021-03-02 12:18 UTC, maltesander reviewed
I just commented on some language. 
There are lots of "will" / "do not" abbreviations. While these may keep a certain closer relationship to the reader, they should not be used in formal language / documents. Although it feels more "young" or "start-up-like" so its maybe not even bad :-). I think we should agree on a level of formality (with or without these abbreviations) in documents like this.

2021-03-02 12:18 UTC, maltesander commented on README.adoc
> +You can either host your own repository, if you so choose, or specify our public repository for convenience.
You can either host your own repository or specify our public repository for convenience.

2021-03-02 12:18 UTC, maltesander commented on README.adoc
> +Depending on which products you want to manage with the Stackable platform you will want to install at least one of our operators.
Depending on the products you want to manage with the Stackable platform, you need to install our corresponding operators.

2021-03-03 08:35 UTC, ohessel commented on README.adoc
> +
I'd add an example here - as done below for the agent or add a link to the respective project in github

===== RHEL

    *coming soon*

===== Ubuntu

    apt-get install stackable-spark-operator-server

2021-03-04 06:43 UTC, fwaibel commented on README.adoc
> +
👍

2021-03-04 06:56 UTC, fwaibel commented on README.adoc
> +` systemctl start stackable-agent`
The extra space before systemctl breaks the formatting

2021-03-04 06:56 UTC, fwaibel commented on README.adoc
> +` systemctl enable stackable-agent`
The extra space before systemctl breaks the formatting

2021-03-04 06:59 UTC, fwaibel commented on README.adoc
> +When you run `kubectl nodes get` on the orchestrator, you should see the objects that all your agents added to indicate their readiness.
The arguments seem to be permuted: `kubectl get nodes` worked fine.

2021-03-09 09:15 UTC, lfrancke requested changes

2021-03-09 09:15 UTC, lfrancke commented on README.adoc
> +That being said, Stackable will work with any Kubernetes, please feel free to skip this chapter if you already have a working Kubernetes cluster, or want to use a managed Kubernetes offering like the
Are we sure they allow custom nodes?
(IONOS do but the others?)
Maybe add a note that we haven't tested them.

2021-03-09 09:15 UTC, lfrancke commented on README.adoc
> +If you choose to follow one of the options mentioned above, feel free to skip ahead to https://xxx[xxx], as you won't need the information in the rest of this chapter.
....

2021-03-09 09:15 UTC, lfrancke commented on README.adoc
> +Since you are still reading this we'll assume that you don't have easy access to an existing Kubernetes and instead install one.
This reads weird "instead install one". Maybe we can just remove this sentence?

2021-03-09 09:15 UTC, lfrancke commented on README.adoc
> +Run the following command on your _orchestrator_ server:
You used `node` above instead of `server`

2021-03-09 09:15 UTC, lfrancke commented on README.adoc
> +    curl -sfL https://get.k3s.io | sh -
Maybe mention something about versions?
We only tested Kubernetes 1.18 and above.

2021-03-09 09:15 UTC, lfrancke commented on README.adoc
> +==== Distribute KubeConfig
You use KubeConfig and Kubeconfig. Not sure which is correct but it'd be best to be consistent.

2021-03-09 09:15 UTC, lfrancke commented on README.adoc
> +  name: repositories.stable.stackable.de
We should change this to stackable.tech (also in the group below)
This'll probably need a follow-up issue in the agent?

2021-03-09 09:15 UTC, lfrancke commented on README.adoc
> +The distributed component of the Stackable Platform is the agent, which needs to be installed on all managed servers and configured to have access to Kubernetes.
"The distributed component" reads weid and doesn't make sense to me.

```suggestion
Tthe agent needs to be installed on all servers that should run services and they need to be configured to have access to Kubernetes.
```
Or similar

2021-03-09 09:15 UTC, lfrancke commented on README.adoc
> +Installing the agent can be done from our rpm and deb package repositories, which we enabled when preparing the nodes above.
```suggestion
Installing the agent can be done from our RPM and deb package repositories, which we enabled when preparing the nodes above.
```

2021-03-09 09:15 UTC, lfrancke commented on README.adoc
> +If you have provided a KUBECONFIG for the root user in `/root/.kube/config` then the agent will use this, if you decided against a _global_ KUBECONFIG, you will need to specify where the config shoul
Again consistency, KUBECONFIG vs KubeConfig vs Kubeconfig

2021-03-09 09:15 UTC, lfrancke commented on README.adoc
> +
```suggestion

[source,yaml]
```

2021-03-09 09:15 UTC, lfrancke commented on README.adoc
> +
```suggestion

[source,bash]
```

Not sure if that works

2021-03-09 09:15 UTC, lfrancke commented on README.adoc
> +
```suggestion

[source,bash]
```
see above

2021-03-09 11:12 UTC, soenkeliebau commented on README.adoc
> +  name: repositories.stable.stackable.de
I'll need to check in the agent, but most probably, yes. Can we leave as is for now to get this merged?

2021-03-09 11:19 UTC, soenkeliebau commented on README.adoc
> +If you have provided a KUBECONFIG for the root user in `/root/.kube/config` then the agent will use this, if you decided against a _global_ KUBECONFIG, you will need to specify where the config shoul
KUBECONFIG in this case refers to an environment variable, which by convention should be spelled in all caps I believe. I've fixed the other occurrences to all lower case which seems to be consistend with the kubernetes config.
https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/

2021-03-09 11:52 UTC, lfrancke requested changes

2021-03-09 11:52 UTC, lfrancke commented on README.adoc
> +NODE: We have tested our stack with Kubernetes 1.18 and above
```suggestion
NOTE: We have tested our stack with Kubernetes 1.18 and above
```

2021-03-09 11:52 UTC, lfrancke commented on README.adoc
> +If you have provided a kubeconfig for the root user in `/root/.kube/config` then the agent will use this, if you decided against a _global_ `KUBECONFIG` enwironment variable, you will need to specify
```suggestion
If you have provided a kubeconfig for the root user in `/root/.kube/config` then the agent will use this, if you decided against a _global_ `KUBECONFIG` environment variable, you will need to specify where the config should be read from.
```

2021-03-09 11:52 UTC, lfrancke commented on README.adoc
>  ==== Distribute KubeConfig
This is still off?

2021-03-09 12:29 UTC, lfrancke approved these changes

2021-03-09 12:31 UTC, merged