ADR009 Placement of services on nodes
stackabletech/documentation pull request #51
Opened 2021-03-01 20:32 UTC by lfrancke

2021-03-01 20:50 UTC, soenkeliebau requested changes

2021-03-01 20:50 UTC, soenkeliebau commented on adr/ADR009-selector_support.adoc
> += ADR009: Placement of services on nodes
When I first saw this title I totally misunderstood it, as my first association was "where on the nodes should we put the services" - but that may just be me.

2021-03-01 20:50 UTC, soenkeliebau commented on adr/ADR009-selector_support.adoc
> +We need to decide on a syntax and feature set on how to place services on nodes.
With reference to my comment from above one or two additional sentences what exactly we are trying to solve here might make sense. Someone without the background knowledge of our discussions today may - at this point - struggle to understand this.

2021-03-01 20:50 UTC, soenkeliebau commented on adr/ADR009-selector_support.adoc
> +* Status: accepted
I think, and I may be mistaken here, that I've always tried keeping the two status in sync..

2021-03-01 20:50 UTC, soenkeliebau commented on adr/ADR009-selector_support.adoc
> +** Lars Francke
Should we add Malte and myself here?

2021-03-03 07:22 UTC, fwaibel commented on adr/ADR009-selector_support.adoc
> +For us it's often the case that users have dedicated hardware for this use-case and all machines should be used and at the same time there are often special nodes reserved for special tasks (e.g. mor
Following the discussion from yesterday: e.g. machines equipped with GPUs

2021-03-08 11:52 UTC, lfrancke commented on adr/ADR009-selector_support.adoc
> +We need to decide on a syntax and feature set on how to place services on nodes.
Do you have a suggestion for me? Happy to change this and also the title.

2021-03-09 22:04 UTC, lfrancke commented on adr/ADR009-selector_support.adoc
> += ADR009: Placement of services on nodes
I've now used "assign" 
From here: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/
Is that better?

2021-03-10 20:14 UTC, soenkeliebau commented on adr/ADR009-selector_support.adoc
> +We need to decide on a syntax and feature set on how to place services on nodes.
Maybe something along the lines of 

> Basically for every running process of a service the user needs to be able to somehow specify on which host(s) this should be run. This specification could be a regular expression over hostnames, exact matches on the hostname, some form of tagging, selecting via system properties, etc.

2021-03-16 15:28 UTC, soenkeliebau requested changes
One syntax issue I think, but content wise only a single comment/question

2021-03-16 15:28 UTC, soenkeliebau commented on adr/ADR009-selector_support.adoc
> +* At the top level there is one property per role
This doesn't render correctly for me due to a missing blank line.

2021-03-16 15:28 UTC, soenkeliebau commented on adr/ADR009-selector_support.adoc
> +* Each role group can have optional `instances` and `instancesPerNode` fields
Should we maybe explicitly mention that this is a operator specific example and might look different for every product?

2021-03-19 11:39 UTC, lfrancke commented on adr/ADR009-selector_support.adoc
> +* Each role group can have optional `instances` and `instancesPerNode` fields
Well, maybe I misunderstand you but my intention was to actually have this the same across all our operators?

2021-03-19 16:17 UTC, soenkeliebau commented on adr/ADR009-selector_support.adoc
> +* Each role group can have optional `instances` and `instancesPerNode` fields
In that case we actually had different understandings, yes. I thought we'd forego the roles for operators that don't need it, but I see the sense in having this consistent!

2021-03-24 09:45 UTC, soenkeliebau requested changes
Changes look good to me, just one comment left open.

2021-03-25 10:02 UTC, lfrancke commented on adr/ADR009-selector_support.adoc
> +We need to decide on a syntax and feature set on how to place services on nodes.
I have chosen a different text but added something. Please take a look.

2021-03-25 10:04 UTC, soenkeliebau approved these changes

2021-03-25 10:05 UTC, merged