Feature/arm experimental
stackabletech/documentation pull request #527
Opened 2024-01-16 09:49 UTC by Maleware

First draft of an small article about early access to our arm64 images

2024-01-30 12:57 UTC, fhennig commented on modules/concepts/pages/experimental-arm64-support.adoc
> +```
```suggestion
[source,bash]
----
stackablectl demo install nifi-kafka-druid-earthquake-data --skip-release -s stacks/stacks-v2.yaml -d demos/demos-v2.yaml
----
```

This is how you do code blocks in asciidoc ;)

2024-02-20 09:03 UTC, Maleware commented on modules/concepts/pages/experimental-arm64-support.adoc
> +```
Thanks! Haven't seen your review till now. Appreciated!

2024-02-27 07:23 UTC, Maleware commented on modules/concepts/pages/experimental-arm64-support.adoc
> +NOTE: Only 23.11.0 is working at this moment.
Fine :)

2024-02-27 08:04 UTC, adwk67 submitted a review, later dismissed
lgtm!

2024-02-27 08:06 UTC, fhennig requested changes
I'd suggest to rename the file to "arm64-support.adoc" (so no experimental) but add the experimental to the title (i.e. "Multi-architecture for SDP (experimental").

Otherwise if we stabilize this feature, the link will change, and that will be annoying.

2024-02-27 08:06 UTC, fhennig commented on modules/concepts/pages/experimental-arm64-support.adoc
> +:page-aliases: arm_support.adoc
```suggestion
```

Don't add this page alias, it's only for legacy pages.

2024-02-27 09:06 UTC, fhennig approved these changes
perfect, thanks!

2024-02-27 09:07 UTC, merged

2024-02-27 15:37 UTC, lfrancke commented on modules/concepts/pages/arm64-support.adoc
> +You will need access to a Kubernetes Cluster and to have the stackablectl https://docs.stackable.tech/home/stable/quickstart[command-line tool] installed.
Is stackablectl available as an ARM version?

2024-02-27 16:42 UTC, Maleware commented on modules/concepts/pages/arm64-support.adoc
> +As they are not available by default so you need to first switch to the `stackable-experimental` organization before pulling them for use with the data platform.
Through our default access ways. Default refers to `docker.stackable.tech/stackable/...`.  

I understand you need to somehow know what I mean. Is this more clear? :

switch from `docker.stackable.tech/stackable` to `docker.stackable.tech/stackable-experimental` before pulling images from the repository.

2024-02-27 16:43 UTC, Maleware commented on modules/concepts/pages/arm64-support.adoc
> +You will need access to a Kubernetes Cluster and to have the stackablectl https://docs.stackable.tech/home/stable/quickstart[command-line tool] installed.
Yes https://docs.stackable.tech/management/stable/stackablectl/installation#_macos

2024-03-04 07:55 UTC, Maleware commented
https://deploy-preview-558--stackable-docs.netlify.app/home/nightly/concepts/arm64-support current WIP

Currently deployed:
https://docs.stackable.tech/home/nightly/concepts/arm64-support