Add ADR to define default paths used by OS packages and agent
stackabletech/documentation pull request #53
Opened 2021-03-12 22:50 UTC by soenkeliebau

I've briefly documented what I believe should be the correct OS paths for some of the things we need to keep on disk.

I think this is correct according to https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.html but have my doubts, whether it makes sense in all cases.

Specifically I wonder about 

1. /etc/opt/stackable - I have not often seen /etc/opt used for configuration.
2. Packages - do we want to keep these in /opt under our folder root as well?
3. Service configs, similar question, should those be somewhere else then /etc/opt/stackable/serviceconfig maybe a level up at /etc/opt/serviceconfig to clearly separate them from config for our components?

2021-03-16 14:59 UTC, soenkeliebau commented
I've updated this and it is now ready for review @lfrancke

2021-03-19 11:16 UTC, lfrancke requested changes

2021-03-19 11:16 UTC, lfrancke commented on adr/ADR011-directory_structure.adoc
> +Instead I have added excerpts from the https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.html[Filesystem Hierarchy Standard] to illustrate why I think the chosen paths are the correct ones.
```suggestion
Instead, I have added excerpts from the https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.html[Filesystem Hierarchy Standard] to illustrate why I think the chosen paths are the correct ones.
```

2021-03-19 11:16 UTC, lfrancke commented on adr/ADR011-directory_structure.adoc
> +We decided to deviate from what the https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.html[Filesystem Hierarchy Standard] specifies a little bit, in order to make the file location more familiar t
```suggestion
We decided to deviate from what the https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.html[Filesystem Hierarchy Standard] specifies, in order to make the file location more familiar to our users.
```

2021-03-19 11:16 UTC, lfrancke commented on adr/ADR011-directory_structure.adoc
> +│   └── stackable
There's NBSPs all over the place here. Intentionally?

2021-03-19 11:16 UTC, lfrancke commented on adr/ADR011-directory_structure.adoc
> +As this is is also third party software but being used by Stackable we will install these under `/opt/stackable/' as well, but put them under a subdirectory `packages` to keep them separate from the
```suggestion
As this is also third party software but being used by Stackable we will install these under `/opt/stackable/' as well, but put them under a subdirectory `packages` to keep them separate from the Stackable software.
```

2021-03-19 11:16 UTC, lfrancke commented on adr/ADR011-directory_structure.adoc
> +Out of the current components, only the agent requires a config file that will be kept here.
I think this whole paragraph can go. It doesn't age well and it's not about "architecture" but a specific implementation.

2021-03-19 11:16 UTC, lfrancke commented on adr/ADR011-directory_structure.adoc
> +Following the logic from above, config files that are written for the actual services that are managed by Stackable (Apache Kafka, Apache Hadoop, ...) should also reside in `/etc/opt/stackable`.
"Following the logic from above" two times in a row but with two different conclusions. I know what you're getting at but it reads weird.

Maybe something like "As outlined above" oder "According to the standard"

2021-03-19 11:16 UTC, lfrancke commented on adr/ADR011-directory_structure.adoc
> +This only refers to the default setting the agent is configured with though, this path can be freely chosen by the user.
Agent specifics again

2021-03-19 11:16 UTC, lfrancke commented on adr/ADR011-directory_structure.adoc
> +=== Agent Working Directory
Again: I don't think we should/need to document specific things.

This could be about "working data" or just "data directories" or "variable data"

2021-03-26 09:02 UTC, soenkeliebau commented on adr/ADR011-directory_structure.adoc
> +│   └── opt
That is on purpose to keep the directory tree looking right. I can also replace them if you think this is an issue..

2021-03-26 09:08 UTC, soenkeliebau commented on adr/ADR011-directory_structure.adoc
> +In accordance with https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.html#optAddonApplicationSoftwarePackages[3.13.1] we will install the binaries for our components under `/opt/stackable/<package
I've changed it to be the document title and the section number.

2021-03-26 09:15 UTC, soenkeliebau commented on adr/ADR011-directory_structure.adoc
> +Out of the current components, only the agent requires a config file that will be kept here.
My intention for this ADR was actually to "tie down" as many specific paths as possible, so "specific implementation" was what I was going for :)

Sounds to me like we have a fundamentally different view in this case. I agree that the name "architectural" hints at only tackling overall architectural things in there, but I think there is value in having one central place where you can look up the paths used by our plattform.

2021-03-26 09:23 UTC, soenkeliebau commented
I have addressed a few comments, some are  still left open due to a fundamental question about what we want to use ADRs for .
I was planning to update this ADR as we go along and have it be the source of truth for all os paths that the Stackable Platform uses, hence also included specifics in it. 
@larsfrancke is of the opinion that we should keep this generic and leave implementation details out of it.

At the end of the day I am fine either way, but if we make this generic, then I think we should have a page detailing the paths somewhere else in the docs..

Anyone else have any thoughts on this?

2021-03-26 11:00 UTC, lfrancke commented on adr/ADR011-directory_structure.adoc
> +Out of the current components, only the agent requires a config file that will be kept here.
I agree but that should - in my opinion - be the end-user documentation.

2021-03-29 09:49 UTC, lfrancke approved these changes

2021-03-30 07:20 UTC, merged