Add a section on Export Controls
stackabletech/documentation pull request #545
Opened 2024-02-08 12:22 UTC by lfrancke

2024-02-08 13:19 UTC, lfrancke commented
Requested review by lawyer toda.

2024-02-12 13:28 UTC, fhennig commented
> The link in the navbar is now dead for 23.11 and previous releases, do we need to back port it somehow or what would you suggest?

Oh, good point, this is actually also the case for the other pages in that menu. Yes I believe backporting them would be the easiest in this case. It also makes sense since the information applies to all releases.

2024-02-12 13:56 UTC, lfrancke commented
Thank you for the offer.

Yes, please do put it on the board and work on it at when you have the time.

2024-02-13 13:40 UTC, fhennig commented
https://github.com/stackabletech/documentation/issues/547 done

2024-02-14 14:11 UTC, adwk67 requested changes

2024-02-14 14:11 UTC, adwk67 commented on modules/ROOT/pages/export.adoc
> +The USA have the https://en.wikipedia.org/wiki/Export_Administration_Regulations[Export Administration Regulations (EAR)] as the primary regulation to control export.
```suggestion
The USA adopts the https://en.wikipedia.org/wiki/Export_Administration_Regulations[Export Administration Regulations (EAR)] as the primary regulation to control exports.
```

2024-02-14 14:11 UTC, adwk67 commented on modules/ROOT/pages/export.adoc
> +NOTE: That means E-Mail notifications to the NSA and BIS are not required and therefore not published here.
```suggestion
NOTE: That means E-Mail notifications to the NSA and BIS are not required and are therefore not published here.
```

2024-02-14 14:11 UTC, adwk67 commented on modules/ROOT/pages/export.adoc
> +* We are exempt under https://www.ecfr.gov/current/title-15/subtitle-B/chapter-VII/subchapter-C/part-734/section-734.3[EAR 734.3(b)] because we are published according to https://www.ecfr.gov/current
```suggestion
* We are exempt under https://www.ecfr.gov/current/title-15/subtitle-B/chapter-VII/subchapter-C/part-734/section-734.3[EAR 734.3(b)] because we publish according to https://www.ecfr.gov/current/title-15/subtitle-B/chapter-VII/subchapter-C/part-734/section-734.7[EAR 734.7]
```

2024-02-14 14:11 UTC, adwk67 commented on modules/ROOT/pages/export.adoc
> +* We are exempt under https://www.ecfr.gov/current/title-15/subtitle-B/chapter-VII/subchapter-C/part-734/section-734.7[EAR 742.15(b)] as all our software only includes https://ecfr.io/Title-15/Sectio
```suggestion
* We are exempt under https://www.ecfr.gov/current/title-15/subtitle-B/chapter-VII/subchapter-C/part-742/section-742.15[EAR 742.15(b)] as our software includes only https://ecfr.io/Title-15/Section-772.1[standard encryption]
```

2024-02-14 15:09 UTC, lfrancke commented on modules/ROOT/pages/export.adoc
> +* We are exempt under https://www.ecfr.gov/current/title-15/subtitle-B/chapter-VII/subchapter-C/part-734/section-734.3[EAR 734.3(b)] because we are published according to https://www.ecfr.gov/current
Thanks for catching this

2024-02-14 15:11 UTC, lfrancke commented
Thanks for the review and the suggestions

2024-02-14 15:11 UTC, adwk67 approved these changes
LGTM

2024-02-14 15:15 UTC, merged