Documentation for SBOMs
stackabletech/documentation pull request #552
Opened 2024-02-22 09:32 UTC by dervoeti

It is explained how to browse through, manually validate and enforce the presence of SBOMs.

2024-02-23 12:46 UTC, dervoeti commented
Thanks for the feedback! Fixed all of it. Also replaced underscores with hyphens in my other docs.

2024-02-24 14:10 UTC, fhennig requested changes
Just one thing, thanks for the changes!

2024-02-24 14:10 UTC, fhennig commented on modules/tutorials/pages/viewing-and-verifying-sboms.adoc
> +----
```suggestion
----
cosign verify-attestation --type cyclonedx \
--certificate-identity-regexp \
'^https://github.com/stackabletech/.+/.github/workflows/.+@.+' \
--certificate-oidc-issuer https://token.actions.githubusercontent.com \
docker.stackable.tech/stackable/airflow-operator:24.3.0 \
| jq '.payload' -r | base64 -d | jq '.predicate'
----
```

The command wasn't copy-pastable anymore, this should fix it.

2024-02-26 08:15 UTC, fhennig approved these changes
:+1:

2024-02-26 08:16 UTC, merged