Suggested changes for ARM docs
stackabletech/documentation pull request #558
Opened 2024-02-27 15:37 UTC by lfrancke

2024-02-28 08:15 UTC, Maleware requested changes
Addressed your comments from https://github.com/stackabletech/documentation/pull/527

Thanks for your effort :)

2024-02-28 08:15 UTC, Maleware commented on modules/concepts/pages/arm64-support.adoc
> +They are not available by default, so you need to switch to the `stackable-experimental` organization before pulling them for use with the data platform.
```suggestion
They are not available by default, so you need to switch to the `stackable-experimental` organization before pulling them.
E.g.
[source,bash]
----
docker pull docker.stackable.tech/stackable-experimental/secret-operator:23.11.0
----
```

2024-02-28 08:15 UTC, Maleware commented on modules/concepts/pages/arm64-support.adoc
>  WARNING: You have to install every operator you need for a given demo individually with helm using `--skip-release` with stackablectl. Otherwise, it will try to install x86 operators and pull ARM64 p
```suggestion
WARNING: You have to install every operator you need for a demo individually with helm. Then installing the specific demo using `--skip-release` with `stackablectl`. Otherwise, `stackablectl` will try to install x86 operators.
```

2024-02-28 08:15 UTC, Maleware commented on modules/concepts/pages/arm64-support.adoc
> +TODO: Change this
```suggestion

```

2024-02-28 08:44 UTC, fhennig submitted a review, later dismissed

2024-02-28 08:44 UTC, fhennig commented on modules/concepts/pages/arm64-support.adoc
> +=== Available Releases
```suggestion
=== Available releases
```
use sentence case in headings

2024-02-28 08:44 UTC, fhennig commented on modules/concepts/pages/arm64-support.adoc
>  === Prepared Demos
```suggestion
=== Prepared demos
```

2024-02-28 08:44 UTC, fhennig commented on modules/concepts/pages/arm64-support.adoc
> +== Early Access
```suggestion
== Early access
```

2024-03-01 10:40 UTC, lfrancke commented on modules/concepts/pages/arm64-support.adoc
>  WARNING: You have to install every operator you need for a given demo individually with helm using `--skip-release` with stackablectl. Otherwise, it will try to install x86 operators and pull ARM64 p
This does not help me understand. I made a different proposal.

2024-03-04 09:21 UTC, Maleware commented
Thanks for your work Lars. You can omit my comments and resolve conversations!

2024-03-04 09:21 UTC, Maleware approved these changes
LGTM! Thank you for your rework, appreciated.

2024-03-06 15:58 UTC, Maleware approved these changes
LGTM!

2024-03-06 16:08 UTC, merged