Release notes for 24.3
stackabletech/documentation pull request #565
Opened 2024-03-18 16:03 UTC by razvan

- **docs: started 24.3 release notes**
- **add headings**
- **fix indentation of new headings**
- **add headings template to comments for the next release**
- **add HDFS breaking changes**
- **Add new and deprecated versions**
- **Add removed versions**
- **supported k8s versions**
- **breaking changes for airflow**
- **more breaking changes**

2024-03-19 13:51 UTC, fhennig commented
What about the UserInfoFetcher for OPA? That was quite a big thing!

2024-03-19 14:26 UTC, fhennig commented
also sboms.stackable.tech and crds.stackable.tech

2024-03-19 14:38 UTC, razvan commented
> What about the UserInfoFetcher for OPA? That was quite a big thing!

Would you add more [here](https://github.com/stackabletech/documentation/pull/565/files#diff-30266bed0ce9f5af64f2f7a6129e1fdf919172b7a4974814010e029b652b8150R56) ?

2024-03-19 16:02 UTC, adwk67 commented on modules/ROOT/pages/release-notes.adoc
> +Almost all product images have been updated to their latest versions. Some notable examples are Apache Airflow 2.8.1, Trino 422 and Apache Spark 2.5.1. In addition, we started building product binari
```suggestion
Almost all product images have been updated to their latest versions. Some notable examples are Apache Airflow 2.8.1, Trino 422 and Apache Spark 3.5.1. In addition, we started building product binaries from source instead of packaging them from the official releases. This enables greater control over the features and the security aspects of the products. Currently Apache Hadoop and Apache HBase are built from source and others will follow in coming releases.
```

2024-03-19 16:04 UTC, adwk67 commented on modules/ROOT/pages/release-notes.adoc
> +Starting with this release, user **authorization** is consistent across all products. The Open Policy Agent has been at the core of the platform since the beginning and in this release we enhanced it
This sounds like every product uses OPA authorization: should we qualify that?
```suggestion
Starting with this release, user **authorization** is consistent across all products. The Open Policy Agent has been a core component of the platform since the beginning and in this release we enhanced its capability with the inclusion of a new component called `user-info-fetcher`. It allows for authorization policies to be built on many attributes like organizational group membership, resource assignment and much more. The first major identity provider supported by the `user-info-fetcher` is Keycloak but others will follow.
```

2024-03-19 16:05 UTC, adwk67 commented on modules/ROOT/pages/release-notes.adoc
> +OpenID Connect is the de-facto authorization standard on the Web and it's making it's way into enterprise environments. Apache Superset and Trino are the first products to add support for it.
```suggestion
OpenID Connect is the de-facto authorization standard on the Web and it's making its way into enterprise environments. Apache Superset and Trino are the first products to add support for it.
```

2024-03-19 16:07 UTC, adwk67 commented on modules/ROOT/pages/release-notes.adoc
> +We are constantly working on improving the platform documentation and custom resource definitions are big part of that. The CRD documentation is now generated automatically and can be found at https:
```suggestion
We are constantly working on improving the platform documentation and custom resource definitions are a significant part of that. The CRD documentation is now generated automatically and can be found at https://crds.stackable.tech.
```

2024-03-19 16:09 UTC, adwk67 commented on modules/ROOT/pages/release-notes.adoc
> +Following are selected product features provided by new versions available in this release:
```suggestion
The following are selected product features provided by new versions available in this release:
```

2024-03-19 16:11 UTC, adwk67 commented on modules/ROOT/pages/release-notes.adoc
> +A new https://github.com/stackabletech/stackable-cockpit[project] called Stackable Cockpit has been started. It is a web-based management tool that allows users to interact with the Stackable data pl
Is cockpit new in 24.3? I thought we mentioned it in 23.11
```suggestion
A new https://github.com/stackabletech/stackable-cockpit[project] called Stackable Cockpit has been started. It is a web-based management tool that allows users to interact with the Stackable data platform. The repository also contains the `stackablectl` command line tool which has been refactored for performance and stability.
```

2024-03-19 16:11 UTC, adwk67 commented on modules/ROOT/pages/release-notes.adoc
> +* `4.14`
Should we add 4.13 in here as we are probably going to certify against that version as well as 4.14/4.15?

2024-03-19 16:12 UTC, adwk67 commented on modules/ROOT/pages/release-notes.adoc
> +The Secret must contain credentials for Airflow `admin` user as well, connection properties to the database and Redis as shown below.
```suggestion
The Secret must contain credentials for Airflow `admin` user as well as connection properties to the database and Redis as shown below.
```

2024-03-19 16:19 UTC, adwk67 commented on modules/ROOT/pages/release-notes.adoc
> +Starting with this release, user **authorization** is consistent across all products. The Open Policy Agent has been a core component of the platform since the beginning and in this release we enhanc
We could also mention here the integration of hadoop with OPA rego rules: https://github.com/stackabletech/hdfs-operator/issues/400
And also rack awareness (maybe under a separate item): https://github.com/stackabletech/hdfs-operator/issues/325

2024-03-19 16:19 UTC, razvan commented on modules/ROOT/pages/release-notes.adoc
> +* `4.14`
I didn't do it because:
* we never tested anything on it
* 4.13 is _only_ on RedHat "maintenance support" until November.

2024-03-19 17:33 UTC, razvan commented on modules/ROOT/pages/release-notes.adoc
> +Starting with this release, user **authorization** is consistent across all products. The Open Policy Agent has been a core component of the platform since the beginning and in this release we enhanc
Indeed: https://github.com/stackabletech/documentation/pull/565/commits/fdce274b2ecca35dd655ad6b6ac072e9a597118f

2024-03-20 08:05 UTC, adwk67 commented on modules/ROOT/pages/release-notes.adoc
> +* `4.14`
OK, let's update that once we have certified the operators.

2024-03-20 08:05 UTC, adwk67 commented on modules/ROOT/pages/release-notes.adoc
> +Starting with this release, user **authorization** is consistent across all products. The Open Policy Agent has been a core component of the platform since the beginning and in this release we enhanc
Thank!

2024-03-24 19:25 UTC, lfrancke commented on modules/ROOT/pages/release-notes.adoc
> +Apache Airflow requires a database to store metadata.
I don't really understand what is breaking here, same for Superset.

2024-03-25 08:29 UTC, maltesander commented on modules/ROOT/pages/release-notes.adoc
> +Some notable examples are Apache Airflow 2.8.1, Trino 422 and Apache Spark 3.5.1.
```suggestion
Some notable examples are Apache Airflow 2.8.1, Trino 442 and Apache Spark 3.5.1.
```

2024-03-25 08:58 UTC, razvan commented on modules/ROOT/pages/release-notes.adoc
> +Apache Airflow requires a database to store metadata.
Yeah, the title of the breaking PR is confusing and doesn't really match the contents. A had a closer look and tried to clarify: https://github.com/stackabletech/documentation/pull/565/commits/9bd8c6e670c2c1f5cfb643507daad1c7fcb3f134

2024-03-25 09:39 UTC, lfrancke requested changes

2024-03-25 09:45 UTC, fhennig approved these changes
We want to go ahead and prepare the docs for release.

Any further changes @lfrancke please make a new PR aftewards, we can cherry-pick the changes over too. We just want to have the new docs in a branch etc ready.

2024-03-25 09:52 UTC, lfrancke approved these changes

2024-03-25 09:52 UTC, lfrancke commented on modules/ROOT/pages/release-notes.adoc
> +// TODO: Link to docs - apparently the README in in the linked repository is all there is.
Resolving for now just to get it merged but I'd like to get input on this.

2024-03-25 09:56 UTC, merged