Add playbook to only build dev version
stackabletech/documentation pull request #579
Opened 2024-03-28 13:55 UTC by sbernauer

To speed up feedback loop

2024-03-28 13:58 UTC, soenkeliebau commented
Can we pull out the branches into a var '[main, 23.11, ...]'and override that with '[main]' for the dev only run, instead of duplicating the entire playbook?

2024-04-02 06:58 UTC, sbernauer commented
What var are you referring to? yaml anchors or is this an Ansible playbook? Looking at https://docs.antora.org/antora/latest/playbook/ I can't find any concept of variables.

I think I would prefer yaml anchors anyway and we could do some 'yq'' magic in the Makefile

2024-04-02 07:00 UTC, fhennig commented
It's possible to specify `content.branches` directly: https://docs.antora.org/antora/latest/playbook/configure-content-sources/

So you don#t have to configure branches per source. 

What do you mean with a var though? @soenkeliebau

2024-04-02 07:10 UTC, soenkeliebau commented
> What do you mean with a var though? @soenkeliebau

I was being stupid and mistook this for Ansible :(

2024-04-02 07:46 UTC, fhennig approved these changes

2024-04-02 07:46 UTC, fhennig commented on Makefile
> +	node_modules/.bin/antora generate only-dev-antora-playbook.yml
I would like to have a make step for local and for only-dev. And maybe the makefile steps should have the same name as the playbooks. So `make build-only-dev` and `make build-local`?

2024-04-02 07:46 UTC, fhennig commented on local-antora-playbook.yml
> +      branches: &branches
I would like to keep this file as it is for a few reasons. There are scripts that rely on the structure of the file being the way it is (part of the release process).

2024-04-02 07:46 UTC, fhennig commented on only-dev-antora-playbook.yml
> +        - main
Not really sure how useful the anchor is here, I feel like it just makes it more complicated without really saving anything.

2024-04-02 07:47 UTC, fhennig requested changes
see above

2024-04-08 07:24 UTC, fhennig commented on Makefile
>  	node_modules/.bin/antora generate local-antora-playbook.yml
```suggestion
build-local: build-ui
	node_modules/.bin/antora generate local-antora-playbook.yml

build-only-dev: build-ui
	node_modules/.bin/antora generate only-dev-antora-playbook.yml
```

either the default recipe needs to be the `local` one, or the `.github/build.yml` needs to be updated to call the `make build-local` explicitly.

README.adoc:25 also just mentions "make", also would need to be updated. 

I'm not sure whether we want the local or only-dev one to be the default. I think i#d like "only-dev" to be the special case and local the default, hmm. Not sure.

thanks for all the other changes, look great!

2024-04-08 08:01 UTC, sbernauer commented on Makefile
>  	node_modules/.bin/antora generate local-antora-playbook.yml
Haha, I though of defaulting to only the dev versions by default.
But I don't have a strong opinion, so picking yours :)

2024-04-08 11:20 UTC, fhennig approved these changes
Alright, thanks!

maybe we can change the default in the future :)

2024-04-09 07:06 UTC, sbernauer commented
Thanks for the review!

2024-04-09 07:12 UTC, merged