docs: release notes for 24.7
stackabletech/documentation pull request #631
Opened 2024-07-23 07:48 UTC by adwk67

2024-07-24 07:33 UTC, sbernauer commented on modules/ROOT/pages/release-notes.adoc
> +=== New / extended platform features
I think it would be awesome to mention that this is the first release supporting multi-arch (x86 and arm)

2024-07-24 07:48 UTC, Techassi commented on modules/ROOT/pages/release-notes.adoc
> +=== stackablectl
Some highlights include:

- New experimental `debug` command
- Pre-built binary for `aarch64-unknown-linux-gnu` available
- Show complete error messages. Some details were cut off previously
- Use latest Go and Rust versions and respective dependiencies

2024-07-24 08:12 UTC, adwk67 commented on modules/ROOT/pages/release-notes.adoc
> +=== New / extended platform features
I've mentioned that further down (I'll change that to experimental as mentioned by Lars in the planning meeting this morning)

2024-07-24 08:13 UTC, adwk67 commented on modules/ROOT/pages/release-notes.adoc
> +=== stackablectl
Thanks!

2024-07-24 08:18 UTC, adwk67 commented on modules/ROOT/pages/release-notes.adoc
> +=== stackablectl
See 7307034

2024-07-24 13:37 UTC, lfrancke requested changes

2024-07-24 13:37 UTC, lfrancke commented on modules/ROOT/pages/release-notes.adoc
> +* Apache HDFS: built from source from release 24.3
```suggestion
* Apache Hadoop HDFS: built from source from release 24.3
```

2024-07-24 13:37 UTC, lfrancke commented on modules/ROOT/pages/release-notes.adoc
> +All Java-based product binaries are now built from source instead of packaging them from the official releases. The status is summarised below:
```suggestion
All Java-based product binaries are now built from source instead of packaging them from the official releases.
The status is summarised below:
```

Style guide says one sentence per line.

2024-07-24 13:37 UTC, lfrancke commented on modules/ROOT/pages/release-notes.adoc
> +* Apache Nifi: built from source from release 24.7
```suggestion
* Apache NiFi: built from source from release 24.7
```

2024-07-24 13:37 UTC, lfrancke commented on modules/ROOT/pages/release-notes.adoc
> +This release is the first fully multi-platform release of the Stackable Data Platform. Each image has a manifest list which wraps the architecture-specific image. The status is still experimental, as
```suggestion
This release is the first fully multi-platform release of the Stackable Data Platform.
Each image has a manifest list which wraps the architecture-specific image.
The status is still experimental, as we work to fine-tune the necessary workflows.
```

2024-07-24 13:37 UTC, lfrancke commented on modules/ROOT/pages/release-notes.adoc
> +Support added for OIDC with/without TLS has been added to Apache Druid in this release.
```suggestion
Support for OIDC with/without TLS has been added to Apache Druid in this release.
```

2024-07-24 13:37 UTC, lfrancke commented on modules/ROOT/pages/release-notes.adoc
> +In this release we provide experimental HBase 2.6.0 support with a new experimental policy based authorizer (with OPA). Check here for xref:hbase:usage-guide/security.adoc#_authorization[HBase author
```suggestion
In this release we provide experimental HBase 2.6.0 support with a new experimental policy based authorizer (with OPA).
Check xref:hbase:usage-guide/security.adoc#_authorization[the documentation on HBase authorization with OPA] but do not rely on its API as it might change in breaking ways during the experimental phase.
```

2024-07-24 13:37 UTC, lfrancke commented on modules/ROOT/pages/release-notes.adoc
> +* Apache Spark: documentation has been showing how to provision Spark dependencies
```suggestion
* Apache Spark: documentation has been added showing how to provision Spark dependencies
```

I assume that's what you meant

2024-07-24 13:37 UTC, lfrancke commented on modules/ROOT/pages/release-notes.adoc
> +* Apache HBase: support for exporting snapshots to S3. The HBase image now depends on the Hadoop image and the required AWS JARs are copied from there to the HBase image. The script https://github.co
We actually do have docs https://docs.stackable.tech/home/nightly/hbase/usage-guide/snapshot-export

2024-07-24 13:37 UTC, lfrancke commented on modules/ROOT/pages/release-notes.adoc
> +* Apache HBase: support for Omid versions 1.1.1 and 1.1.2
Please leave all references to Omid out of the release notes

2024-07-24 13:37 UTC, lfrancke commented on modules/ROOT/pages/release-notes.adoc
> +* Apache Nifi: support specifying the SecretClass that is used to obtain TLS certificates
```suggestion
* Apache NiFi: support specifying the SecretClass that is used to obtain TLS certificates
```

2024-07-24 13:37 UTC, lfrancke commented on modules/ROOT/pages/release-notes.adoc
> +* Open Policy Agent: support enabling decision logs
```suggestion
* Open Policy Agent: support enabling decision logs, this was an often requested feature and helps implement audit logging for authorization decisions
```

2024-07-24 13:37 UTC, lfrancke commented on modules/ROOT/pages/release-notes.adoc
> +* Apache HBase: remove sed calls to replace KRB REALM in configuration. IMPORTANT: This means the operator will ONLY work with HBase versions that are compiled against Hadoop 3.x as of now
```suggestion
* Apache HBase: remove sed calls to replace KRB REALM in configuration. IMPORTANT: This means the operator will ONLY work with HBase versions that are compiled against Hadoop 3.x as of now. This is only relevant if you are building your own images.
```

2024-07-24 13:37 UTC, lfrancke commented on modules/ROOT/pages/release-notes.adoc
> +* Apache hive: move the metastore user and password DB credentials out of the CRD into a Secret containing the keys username and password
```suggestion
* Apache Hive: move the metastore user and password DB credentials out of the CRD into a Secret containing the keys username and password
```

2024-07-24 13:37 UTC, lfrancke commented on modules/ROOT/pages/release-notes.adoc
> +* Apache Nifi: use config-utils for text-replacement of variables in configs. This fixes escaping problems, especially special characters are included in the password
```suggestion
* Apache NiFi: use config-utils for text-replacement of variables in configs. This fixes escaping problems, especially when special characters are included in the password
```

2024-07-24 13:37 UTC, lfrancke commented on modules/ROOT/pages/release-notes.adoc
> +* Secret operator: the TLS CA Secret is now installed into the Namespace of the operator (typically `stackable-operators`), rather than `default`
Question: This is only relevant for openShift right?

2024-07-24 13:37 UTC, lfrancke commented on modules/ROOT/pages/release-notes.adoc
> +* Apache HBase: remove sed calls to replace KRB REALM in configuration. IMPORTANT: This means the operator will ONLY work with HBase versions that are compiled against Hadoop 3.x as of now
I think this can be removed

2024-07-24 13:49 UTC, lfrancke commented on modules/ROOT/pages/release-notes.adoc
> +This release is the first fully multi-platform release of the Stackable Data Platform. Each image has a manifest list which wraps the architecture-specific image. The status is still experimental, as
Reading it a second time: This should spell out ARM and X86 and it should also link to the multi-arch docs

2024-07-24 13:50 UTC, adwk67 commented on modules/ROOT/pages/release-notes.adoc
> +This release is the first fully multi-platform release of the Stackable Data Platform. Each image has a manifest list which wraps the architecture-specific image. The status is still experimental, as
That page seems to have been removed from the nightly docs (or I'm looking in the wrong place)

2024-07-24 13:53 UTC, adwk67 commented on modules/ROOT/pages/release-notes.adoc
> +* Apache HBase: support for Omid versions 1.1.1 and 1.1.2
Done ec856a5.

2024-07-24 13:53 UTC, lfrancke commented on modules/ROOT/pages/release-notes.adoc
> +This release is the first fully multi-platform release of the Stackable Data Platform. Each image has a manifest list which wraps the architecture-specific image. The status is still experimental, as
I also can't find it. I pinged @Maleware

2024-07-24 13:54 UTC, lfrancke commented on modules/ROOT/pages/release-notes.adoc
> +* Apache HBase: remove sed calls to replace KRB REALM in configuration. IMPORTANT: This means the operator will ONLY work with HBase versions that are compiled against Hadoop 3.x as of now
"this" -> the HBase entry

2024-07-24 13:59 UTC, adwk67 commented on modules/ROOT/pages/release-notes.adoc
> +* Apache HBase: support for exporting snapshots to S3. The HBase image now depends on the Hadoop image and the required AWS JARs are copied from there to the HBase image. The script https://github.co
Ah, thanks! Added in 096d092.

2024-07-24 14:08 UTC, adwk67 commented on modules/ROOT/pages/release-notes.adoc
> +* Apache HBase: remove sed calls to replace KRB REALM in configuration. IMPORTANT: This means the operator will ONLY work with HBase versions that are compiled against Hadoop 3.x as of now
Done caa13cb

2024-07-24 14:14 UTC, adwk67 commented on modules/ROOT/pages/release-notes.adoc
> +* Secret operator: the TLS CA Secret is now installed into the Namespace of the operator (typically `stackable-operators`), rather than `default`
Yes, it is. I'll add a note to that effect.

2024-07-24 14:57 UTC, adwk67 commented on modules/ROOT/pages/release-notes.adoc
> +This release is the first fully multi-platform release of the Stackable Data Platform. Each image has a manifest list which wraps the architecture-specific image. The status is still experimental, as
See 29fa81b

2024-07-25 12:20 UTC, sbernauer commented on modules/concepts/pages/multi-platform-support.adoc
> +These tags are then bundled as a manifest list using an automated workflow so that the appropriate image can be transparently selected for the active platform/architecture.
```suggestion
These tags are then bundled as a manifest list using an automated workflow so that the appropriate image can be transparently selected for the active platform/architecture.
This also enables mixed Kubernetes clusters, with amd64 and arm64 nodes being used simulatiously. 
```

2024-07-25 15:05 UTC, lfrancke commented on modules/ROOT/pages/release-notes.adoc
> +* https://github.com/stackabletech/hdfs-operator/pull/545[Apache Hadoop: 3.4.0]
And then we need a warning _somewhere_ in this document saying something along the lines of:

"We do ship Apache Hadoop 3.4.0 but it is a preview only and we do NOT support upgrading from 3.3 to 3.4 at the moment. Please test 3.4 on fresh installations but if you are on 3.3 right now do not attempt to upgrade to 3.4."

2024-07-25 17:29 UTC, adwk67 commented on modules/ROOT/pages/release-notes.adoc
> +* https://github.com/stackabletech/hdfs-operator/pull/545[Apache Hadoop: 3.4.0]
Added in 0187c15

2024-07-25 17:31 UTC, adwk67 commented on modules/ROOT/pages/release-notes.adoc
> +* Apache Hadoop: 3.3.4, 3.3.6
e91ff3b

2024-07-26 08:44 UTC, Maleware commented on modules/ROOT/pages/release-notes.adoc
> +The status is still xref:concepts:multi-platform-support.adoc[experimental], as we work to fine-tune the necessary workflows.
We have to point out that Superset 2.1.3 won't be available on 24.7 for arm64. This version is deprecated in this release and won't be part of 24.11 anymore

2024-07-26 09:44 UTC, adwk67 commented on modules/ROOT/pages/release-notes.adoc
> +The status is still xref:concepts:multi-platform-support.adoc[experimental], as we work to fine-tune the necessary workflows.
I've mentioned thst here:

![image](https://github.com/user-attachments/assets/b7a07a20-c51b-4836-bcc4-e8d83a93a6f9)

2024-07-26 10:18 UTC, Maleware commented on modules/ROOT/pages/release-notes.adoc
> +The status is still xref:concepts:multi-platform-support.adoc[experimental], as we work to fine-tune the necessary workflows.
Woops overlooked it! All right then :)

2024-07-29 09:04 UTC, lfrancke requested changes

2024-07-29 09:04 UTC, lfrancke commented on modules/ROOT/pages/release-notes.adoc
> +* Apache Nifi: 1.23.2
```suggestion
* Apache NiFi: 1.23.2
```

2024-07-29 09:04 UTC, lfrancke commented on modules/concepts/pages/container-images.adoc
> +See xref:concepts:multi-platform-support.adoc[this] page for an overview and the current status.
```suggestion
See our documentation xref:concepts:multi-platform-support.adoc[on multi-platform support] for an overview and the current status.
```

2024-07-29 09:04 UTC, lfrancke commented on modules/concepts/pages/multi-platform-support.adoc
> +Starting with Stackable release 24.7, all images are {multi-platform-images}[multi-platform images], supporting the AMD64 and ARM64 architectures.
```suggestion
Starting with Stackable release 24.7, all images support {multi-platform-images}[multi-platform images] the AMD64 and ARM64 architectures.
```

2024-07-29 09:04 UTC, lfrancke commented on modules/concepts/pages/multi-platform-support.adoc
> +Each product image is built for each platform with a specific tag.
"specific" tag is a bit confusing. What's meant here?

2024-07-29 09:04 UTC, lfrancke commented
Only minor nits left from my end.

2024-07-29 09:07 UTC, adwk67 commented on modules/concepts/pages/multi-platform-support.adoc
> +Each product image is built for each platform with a specific tag.
I mean platform-specific e.g. 2.9.2-stackable24.7.0-amd64 and 2.9.2-stackable24.7.0-arm64

2024-07-29 09:07 UTC, adwk67 commented on modules/concepts/pages/multi-platform-support.adoc
> +Each product image is built for each platform with a specific tag.
i'll make that clearer

2024-07-29 09:08 UTC, lfrancke commented on modules/concepts/pages/multi-platform-support.adoc
> +Starting with Stackable release 24.7, all images are {multi-platform-images}[multi-platform images], supporting the AMD64 and ARM64 architectures.
Wait....this is wrong....I think I missed something in the edit.

2024-07-29 09:09 UTC, lfrancke commented on modules/concepts/pages/multi-platform-support.adoc
> +Starting with Stackable release 24.7, all images are {multi-platform-images}[multi-platform images], supporting the AMD64 and ARM64 architectures.
I think you can ignore this suggestion.

2024-07-29 09:21 UTC, adwk67 commented on modules/concepts/pages/multi-platform-support.adoc
> +Each product image is built for each platform with a specific tag.
See 32ef010

2024-07-29 09:21 UTC, adwk67 commented on modules/concepts/pages/multi-platform-support.adoc
> +Starting with Stackable release 24.7, all images are {multi-platform-images}[multi-platform images], supporting the AMD64 and ARM64 architectures.
Reverted 32ef010

2024-07-29 09:22 UTC, lfrancke requested changes
One last change then I'm happy and could approve.

2024-07-29 09:22 UTC, lfrancke commented on modules/concepts/pages/multi-platform-support.adoc
> +For example, the airflow images with tags `airflow:2.9.2-stackable24.7.0-amd64` and `airflow:2.9.2-stackable24.7.0-arm64` are bundled in the manifest list `airflow:2.9.2-stackable24.7.0` using an aut
```suggestion
For example, the Airflow images with tags `airflow:2.9.2-stackable24.7.0-amd64` and `airflow:2.9.2-stackable24.7.0-arm64` are bundled in the manifest list `airflow:2.9.2-stackable24.7.0` using an automated workflow.
```

2024-07-29 09:30 UTC, lfrancke approved these changes

2024-07-29 09:36 UTC, merged