docs: Add small example of reconciliationPaused feature
stackabletech/documentation pull request #648
Opened 2024-08-14 07:51 UTC by sbernauer

2024-08-16 08:43 UTC, adwk67 requested changes
Just very minor things.

2024-08-16 08:43 UTC, adwk67 commented on modules/concepts/pages/operations/cluster_operations.adoc
> +IMPORTANT: In case you create a stacklet and set `reconciliationPaused` to `true` during the creation, no resources will be created.
```suggestion
IMPORTANT: If you create a stacklet and set `reconciliationPaused` to `true` during the creation, no resources will be created.
```

2024-08-16 08:43 UTC, adwk67 commented on modules/concepts/pages/operations/cluster_operations.adoc
> +This is due to the fact that you basically state "Hey my-operator, here is an MyCluster, but please ignore it".
```suggestion
This is due to the fact that you basically state "Hey, my-operator, here is a MyCluster, but please ignore it".
```

2024-08-16 08:46 UTC, razvan submitted a review, later dismissed

2024-08-16 08:49 UTC, adwk67 submitted a review, later dismissed

2024-08-16 09:17 UTC, NickLarsenNZ requested changes
Will complete the review soon, and also provide a suggestion

2024-08-16 09:17 UTC, NickLarsenNZ commented on modules/concepts/pages/operations/cluster_operations.adoc
> +This is due to the fact that you basically state "Hey, my-operator, here is a MyCluster, but please ignore it".
I would reword it less casually. Will come back with a suggestion soon.

2024-08-19 08:25 UTC, NickLarsenNZ approved these changes
Added my suggestion

2024-08-19 08:25 UTC, NickLarsenNZ commented on modules/concepts/pages/operations/cluster_operations.adoc
> +This is due to the fact that you basically state "Hey, my-operator, here is a MyCluster, but please ignore it".
```suggestion
[IMPORTANT]
===========
When `reconciliationPaused` is set to `true`, operators will ignore reconciliation events (creations, updated, deletions).

Furthermore, if you create a stacklet where `reconciliationPaused` is set to `true`, no resources will be created.
===========
```

2024-08-19 08:46 UTC, sbernauer commented on modules/concepts/pages/operations/cluster_operations.adoc
> +IMPORTANT: In case you create a stacklet and set `reconciliationPaused` to `true` during the creation, no resources will be created.
I did go with @NickLarsenNZ suggestion, hope that works for you

2024-08-19 09:06 UTC, NickLarsenNZ requested changes
Sorry, my suggestion had errors

2024-08-19 09:06 UTC, NickLarsenNZ commented on modules/concepts/pages/operations/cluster_operations.adoc
> +To avoid this, the cluster should first be stopped and then paused.
My apologies, [blocks need (?) to use _four_ `=`](https://docs.antora.org/antora/latest/asciidoc/examples/#delimited). I thought it just had to match :shrug: 

Also, I forgot to delete the previous text in the suggestion.

```suggestion
====
When `reconciliationPaused` is set to `true`, operators will ignore reconciliation events (creations, updates, deletions).

Furthermore, if you create a stacklet where `reconciliationPaused` is set to `true`, no resources will be created.
====
```

2024-08-19 09:08 UTC, NickLarsenNZ approved these changes
LGTM

2024-08-19 09:16 UTC, sbernauer commented on modules/concepts/pages/operations/cluster_operations.adoc
> +To avoid this, the cluster should first be stopped and then paused.
Applied in 688a3e5c

2024-08-19 09:27 UTC, NickLarsenNZ approved these changes
LGTM

2024-08-19 09:28 UTC, merged