Initial commit of maturity levels and operator roadmap (stackabletech#63)
stackabletech/documentation pull request #65
Opened 2021-05-11 08:15 UTC by Jimvin

First commit of maturity levels and operator roadmap.

2021-05-11 08:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/stackabletech/documentation?pullRequest=65) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/stackabletech/documentation?pullRequest=65) before we can accept your contribution.<br/><hr/>**Jim Halfpenny** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/stackabletech/documentation?pullRequest=65) it.</sub>

2021-05-25 13:56 UTC, lfrancke requested changes
As mentioned in the comments this is not written on a "per-component" basis but with the whole platform in mind. We'd like to have the former so we can evolve components independently.

This is also missing things like monitoring, metrics etc.

2021-05-25 13:56 UTC, lfrancke commented on modules/maturity_levels/pages/ML1.adoc
> +The aim for maturity level 1 is to provide an MVP of Stackable, including delivery of the essential components needed to deploy the initial service offerings. This will serve to deliver the essential
Our original intention was to have these maturity levels _per component_. This reads a bit like it covers the whole platform.

2021-05-25 13:56 UTC, lfrancke commented on modules/maturity_levels/pages/ML1.adoc
> +* https://zookeeper.apache.org/[Apache Zookeeper]
```suggestion
* https://zookeeper.apache.org/[Apache ZooKeeper]
```

2021-05-25 13:56 UTC, lfrancke commented on modules/maturity_levels/pages/ML1.adoc
> +Stackable will be provided as a software package and installation of Stackable will via be a documented manual process. This will involve the installation of OS software packages (available as both R
```suggestion
Stackable will be provided as a software package and installation of Stackable will be via a documented manual process. This will involve the installation of OS software packages (available as both RPM and DEB packages) for the Stackable agent, with operators made available as OS packages and docker images. Manual configuration will be required during installation. Prerequisites may be added using the OS package manager when available, with some dependencies needing to be satisfied manually.
```

2021-05-25 13:56 UTC, lfrancke commented on modules/maturity_levels/pages/ML1.adoc
> +Stackable will be able to deploy and configure a service for a given specification presented as a YAML file. It will be able to link a service with its dependencies e.g. associating a Kafka deploymen
```suggestion
Stackable will be able to deploy and configure a service for a given specification presented as a YAML file. It will be able to link a service with its dependencies e.g. associating a Kafka deployment with its ZooKeeper service. Services once deployed can also be shut down and destroyed.
```

2021-05-25 13:56 UTC, lfrancke commented on modules/maturity_levels/pages/ML2.adoc
> +The aim for maturity level 2 is to build on the core foundation of the Stackable platform and ready it for GA release. This will include the introduction of new components to Stackable as well as imp
As mentioned above: The idea was to be able to evolve the maturity of components in the stack independently.

As such we'd always introduce new components at ML1 (or possibly later also at higher levels).
So Kafka for example might already support monitoring, metrics and security but Pulsar (making this up) only supports basic start/stop operations.

2021-05-25 13:56 UTC, lfrancke commented on modules/maturity_levels/pages/ML2.adoc
> +A service registry will allow for registration of deployed services and contain the configuration required for services to interact. This will include service endpoints and client configuration and a
I think this needs to be worded differently.

this is not a wording suggestion: An operator at maturity level 2 supports registering itself with a service registry (e.g. Consul). This is again the confusion between platform-wide levels and operator-specific maturity levels. It might be that we personally don't introduce any service registry for example.

2021-05-25 13:56 UTC, lfrancke commented on modules/maturity_levels/pages/ML2.adoc
> +A managed security framework will be introduced, extending the use of https://www.openpolicyagent.org/[(OPA)] to other Stackable services. Management of OPA policy will be through manually written OP
What's the difference to ML1?

2021-05-28 06:27 UTC, Jimvin commented
Platform ML refactored into its own area and opperaror ML docs added.

2021-05-28 07:45 UTC, Jimvin commented on modules/maturity_levels/pages/ML1.adoc
> +The aim for maturity level 1 is to provide an MVP of Stackable, including delivery of the essential components needed to deploy the initial service offerings. This will serve to deliver the essential
I've refactored the docs to keep the platform-level levels and added docs for individual components

2021-05-28 07:47 UTC, Jimvin commented on modules/maturity_levels/pages/ML1.adoc
> +* https://zookeeper.apache.org/[Apache Zookeeper]
Typo fixed

2021-05-28 07:47 UTC, Jimvin commented on modules/maturity_levels/pages/ML1.adoc
> +Stackable will be provided as a software package and installation of Stackable will via be a documented manual process. This will involve the installation of OS software packages (available as both R
Typo fixed

2021-05-28 07:52 UTC, Jimvin commented on modules/maturity_levels/pages/ML1.adoc
> +Stackable will be able to deploy and configure a service for a given specification presented as a YAML file. It will be able to link a service with its dependencies e.g. associating a Kafka deploymen
Typo fixed

2021-06-07 11:09 UTC, lfrancke requested changes
Some minor changes. I haven't finished the higher PMLs yet but this looks good in general.

2021-06-07 11:09 UTC, lfrancke commented on maturity_levels/components.csv
> +apache_nifi,Apache Nifi,Jim Halfpenny <jim@source321.com>,0.1,26.05.2021,1,1,In development,Data In Motion,,,"Apache ZooKeeper",,https://github.com/stackabletech/nifi-operator,https://nifi.apache.org
Nifi -> NiFi

I'm not going to comment in other places

2021-06-07 11:09 UTC, lfrancke commented on modules/maturity_levels/pages/operators/apache_spark.adoc
> +None
I believe it too requires ZK for HA

2021-06-07 11:09 UTC, lfrancke commented on maturity_levels/templates/apache_hadoop_yarn.j2
> +Apache Hadoop YARN is a framework for job scheduling and cluster resource management.r
```suggestion
Apache Hadoop YARN is a framework for job scheduling and cluster resource management.
```

2021-06-07 11:09 UTC, lfrancke commented on modules/maturity_levels/nav.adoc
> +** xref:platform/ML5.adoc[]
This does not render for me.

```suggestion
* Maturity Levels

** Components
*** xref:operators/operator_maturity_levels.adoc[]
*** xref:operators/apache_kafka.adoc[]
*** xref:operators/apache_nifi.adoc[]
*** xref:operators/apache_spark.adoc[]
*** xref:operators/apache_zookeeper.adoc[]

** Platform
*** xref:platform/platform_maturity_levels.adoc[]
*** xref:platform/ML1.adoc[]
*** xref:platform/ML2.adoc[]
*** xref:platform/ML3.adoc[]
*** xref:platform/ML4.adoc[]
*** xref:platform/ML5.adoc[]
```

2021-06-07 11:09 UTC, lfrancke commented on maturity_levels/templates/apache_spark.j2
> +=== Operator Status
```suggestion
== Operator Status
```

2021-06-07 11:09 UTC, lfrancke commented on modules/maturity_levels/pages/platform/ML1.adoc
> += Platform Maturity Level 1
```suggestion
= Maturity Level 1
```

All other ML* docs don't have the "Plaform"
I don't mind either way but it should be consistent.

2021-06-15 07:24 UTC, soenkeliebau submitted a review, later dismissed
Left a few questions, but mostly that is probably simply "subject to change" as we progress. 
Overall I'm happy to merge this as is as well, that'll give us a documented basis out there that we can work of.

I'm not 100% certain yet how platform and operator maturity levels interact and fit together, but thats probably just another case of something that will need to evolve over time.

2021-06-15 07:24 UTC, soenkeliebau commented on modules/maturity_levels/pages/operators/operator_maturity_levels.adoc
> +* Open Policy Agent integration for authorisation and audit
Will ML1 security be usable without this? I'm not sure if we can get away with not having this in ML1 tbh..

2021-06-15 07:24 UTC, soenkeliebau commented on modules/maturity_levels/pages/operators/operator_maturity_levels.adoc
> +* Operand backups and snapshots
Probably not possible for all products..at least not without a stop the world event..

Backup & DR might need to become a chapter all of its own.

2021-06-15 07:24 UTC, soenkeliebau commented on modules/maturity_levels/pages/operators/operator_maturity_levels.adoc
> +== Level 4 - Smooth Operator
I personally would consider switching levels 3 and 4 - I think monitoring will be more important than a GUI that allow configuring stuff..

2021-06-15 07:24 UTC, soenkeliebau commented on modules/maturity_levels/pages/operators/operator_maturity_levels.adoc
> +* Configuration validation and best practice
Don't we want this earlier?

2021-06-16 14:00 UTC, Jimvin commented on modules/maturity_levels/pages/operators/operator_maturity_levels.adoc
> +* Operand backups and snapshots
No, snapshots might not be meaningful for all components, but could be used at an instance level for rollback of upgrades. DR is nuanced and needs its own architecture and design docs encompassing backups across multiple components.

2021-06-16 14:01 UTC, Jimvin commented on modules/maturity_levels/pages/operators/operator_maturity_levels.adoc
> +* Open Policy Agent integration for authorisation and audit
Good point, moved to ML1. I don't want this to be a hard barrier to entry for operators though, adding OPA support is going to be a tall order for some components.

2021-06-16 14:08 UTC, Jimvin commented on modules/maturity_levels/pages/operators/operator_maturity_levels.adoc
> +* Configuration validation and best practice
Yes, moved to ML2.

2021-06-22 13:08 UTC, lfrancke approved these changes

2021-06-28 07:32 UTC, merged