Add 24.11 Release Notes
stackabletech/documentation pull request #679
Opened 2024-11-15 09:16 UTC by NickLarsenNZ

2024-11-20 09:39 UTC, adwk67 requested changes

2024-11-20 09:39 UTC, adwk67 commented on modules/ROOT/pages/release-notes.adoc
> +* The performance of the https://docs.stackable.tech/home/stable/hdfs/usage-guide/security.html#_authorization[OPA Authorizer] has been greatly improved. This _can_ be a breaking change so please mak
```suggestion
* The performance of the https://docs.stackable.tech/home/stable/hdfs/usage-guide/security.html#_authorization[OPA Authorizer] has been greatly improved. This _can_ be a breaking change so please make sure to read the hdfs-utils https://github.com/stackabletech/hdfs-utils/releases/tag/v0.4.0[release notes] for details.
```

2024-11-20 09:39 UTC, adwk67 commented on modules/ROOT/pages/release-notes.adoc
> +* The User Info Fetcher HTTP API has been replaced with a Rego library, please see https://docs.stackable.tech/home/nightly/opa/usage-guide/user-info-fetcher#_user_info_fetcher_api for more informati
```suggestion
* The User Info Fetcher HTTP API has been replaced with a Rego library. Please see https://docs.stackable.tech/home/nightly/opa/usage-guide/user-info-fetcher#_user_info_fetcher_api for more information
```

2024-11-20 09:39 UTC, adwk67 commented on modules/ROOT/pages/release-notes.adoc
> +* In SDP 24.7 we upgraded the version of [JMX Exporter](https://github.com/prometheus/jmx_exporter) from 0.20 to 1.0.1. This is the tool which allows us to expose JMX as Prometheus metrics and is in
```suggestion
* In SDP 24.7 we upgraded the version of [JMX Exporter](https://github.com/prometheus/jmx_exporter) from 0.20 to 1.0.1. This is the tool which allows us to expose JMX metrics in Prometheus and is in use for Hadoop, HBase, Hive, Kafka, Spark, Trino and ZooKeeper. Unfortunately the version 1.0.1 has a severe performance degradation which has been [fixed upstream](https://github.com/prometheus/jmx_exporter/pull/1009) but is not yet released. This SDP release 24.11 contains a fixed version bringing performance back to normal levels.
```

2024-11-20 09:39 UTC, adwk67 commented on modules/ROOT/pages/release-notes.adoc
> +* Added support for customizing sAMAccountName generation
Is that casing correct? Should that be SamAccountName or SAMAccountName?

2024-11-20 09:39 UTC, adwk67 commented on modules/ROOT/pages/release-notes.adoc
> +* Apache NiFi: allow users to configure allowed hosts when NiFi is running behind a proxy. The proxy host check is now turned off by default. Documentation: https://docs.stackable.tech/home/nightly/n
```suggestion
* Apache NiFi: permit users to configure allowed hosts when NiFi is running behind a proxy. The proxy host check is now turned off by default. Documentation: https://docs.stackable.tech/home/nightly/nifi/usage_guide/security#host-header-check
```

2024-11-20 09:39 UTC, adwk67 commented on modules/ROOT/pages/release-notes.adoc
> +* `4.15`
We are hoping to certify against - and therefore support - 4.16.

2024-11-20 10:36 UTC, maltesander commented on modules/ROOT/pages/release-notes.adoc
> +* Added support for customizing sAMAccountName generation
I just copied the release notes, but quick google search seems to confirm `sAMAccountName`.

2024-11-20 10:37 UTC, maltesander commented on modules/ROOT/pages/release-notes.adoc
> +* `4.15`
Yes, left it out on purpose for now, we can add once we actually tested and / or certified?

2024-11-20 11:48 UTC, Techassi commented on modules/ROOT/pages/release-notes.adoc
> +=== stackablectl
In the stackablectl-24.11.0 release only one thing worth mentioning happened:

> Bump Rust dependencies to fix critical vulnerability in quinn-proto, see [CVE-2024-45311](https://github.com/advisories/GHSA-vr26-jcq5-fjj8) (https://github.com/stackabletech/stackable-cockpit/pull/318).

In the upcoming stackablectl-24.11.1 release, we will have better release sorting and Nushell + Elvish shell completions.

2024-11-20 12:09 UTC, Techassi commented on modules/ROOT/pages/release-notes.adoc
> +=== New / extended platform features
In the last release notes (for 24.7) we had a dedicated section about CVEs (and our vulnerability handling process), see [here](https://docs.stackable.tech/home/stable/release-notes/#_new_extended_platform_features).

Should we add something similar, for example by introducing a new "CVE/Security" section?

CC @dervoeti

2024-11-20 12:26 UTC, maltesander commented on modules/ROOT/pages/release-notes.adoc
> +=== stackablectl
Thanks, added .

2024-11-20 13:24 UTC, maltesander commented on modules/ROOT/pages/release-notes.adoc
> +Monitoring::
Not a fan of the headings or the resulting sorting. Started by trying to sort the features into groups, but not sure anymore. Any better ideas/input?

2024-11-21 10:03 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +kubectl replace -f https://raw.githubusercontent.com/stackabletech/hello-world-operator/24.11.0/deploy/helm/hello-world-operator/crds/crds.yaml
Do we want to normally deploy hello-world-operator? maybe this can go? (same for in the Helm section below)

2024-11-21 10:03 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +> todo: do we mention NiFi 2.0.0 (experimental)? because NiFi 1.27.0 -> 2.0.0 requires manual intervention (basically same as in the 24.7 note)
Should we mention JMX and NiFi 2.0.0 (experimental) here?

2024-11-21 10:15 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +* More than 142 CVEs were fixed in the Stackable product images. This includes 11 CVEs of critical and 55 CVEs of high severity.
```suggestion
* More than 142 CVEs were fixed in the Stackable product images. This includes 11 critical and 55 high-severity CVEs.
```

2024-11-21 10:16 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +> todo: do we mention NiFi 2.0.0 (experimental)? because NiFi 1.27.0 -> 2.0.0 requires manual intervention (basically same as in the 24.7 note)
Also the OIDC issue that @sbernauer found.

2024-11-21 10:17 UTC, Techassi commented on modules/ROOT/pages/release-notes.adoc
> +=== stackablectl
We can add additional items here, as stackablectl-24.11.1 was released.

> We now provide additional completions for Nushell and Elvish, support using SOCK5 and HTTP proxies, and improved the sorting of release versions.

See:

https://github.com/stackabletech/stackable-cockpit/pull/328
https://github.com/stackabletech/stackable-cockpit/pull/336
https://github.com/stackabletech/stackable-cockpit/pull/337

2024-11-21 10:21 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +* The performance of the https://docs.stackable.tech/home/stable/hdfs/usage-guide/security.html#_authorization[OPA Authorizer] has been greatly improved. This _can_ be a breaking change so please mak
This is rendering strangely:

![image](https://github.com/user-attachments/assets/c8040038-bedb-46c7-8067-1a231c8a0c4c)

Probably because of the `_` in the URL.

2024-11-21 10:32 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +* In SDP 24.7 we upgraded the version of [JMX Exporter](https://github.com/prometheus/jmx_exporter) from 0.20 to 1.0.1. This is the tool which allows us to expose JMX metrics in Prometheus and is in
As much as we'd love it to be Markdown, it is not yet... :smile: 

```suggestion
* In SDP 24.7 we upgraded the version of https://github.com/prometheus/jmx_exporter[JMX Exporter] from 0.20 to 1.0.1. This is the tool which allows us to expose JMX metrics in Prometheus and is in use for Hadoop, HBase, Hive, Kafka, Spark, Trino and ZooKeeper. Unfortunately the version 1.0.1 has a severe performance degradation which has been https://github.com/prometheus/jmx_exporter/pull/1009[fixed upstream] but is not yet released. This SDP release 24.11 contains a fixed version bringing performance back to normal levels.
```

2024-11-21 10:39 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +* In SDP 24.7 we upgraded the version of [JMX Exporter](https://github.com/prometheus/jmx_exporter) from 0.20 to 1.0.1. This is the tool which allows us to expose JMX metrics in Prometheus and is in
I'd probably reword it to move the "what JMX is" to the start, and then what the consequence is...

```suggestion
* https://github.com/prometheus/jmx_exporter[JMX Exporter] is a tool which allows us to expose JMX metrics as Prometheus metrics. It is used by the following products: Hadoop, HBase, Hive, Kafka, Spark, Trino and ZooKeeper. In the previous SDP release (24.7) we upgraded JMX Exporter from 0.20 to 1.0.1. Unfortunately version 1.0.1 has a severe performance degradation which has been https://github.com/prometheus/jmx_exporter/pull/1009[fixed upstream] but is not yet released. This SDP release 24.11 contains a fixed version bringing performance back to normal levels.
```

2024-11-21 10:45 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +* Added support for customizing sAMAccountName generation in secret operator.
```suggestion
* Added support for customizing `sAMAccountName` generation in secret operator.
```

2024-11-21 10:53 UTC, Techassi commented on modules/ROOT/pages/release-notes.adoc
> +* Listeners can now be configured to use either IP addresses or DNS hostnames.
```suggestion
* Listeners can now be configured to use either IP addresses or domain names.
```

2024-11-21 10:58 UTC, Techassi commented on modules/ROOT/pages/release-notes.adoc
> +* Apache HBase: The hadoop-azure module was added to the image and is contained in the classpath. This makes it possible to use the Azure Data Lake Storage Gen2 (ADLS) instead of HDFS. See the usage
We should add a link to the usage guide here:

```suggestion
* Apache HBase: The hadoop-azure module was added to the image and is contained in the classpath. This makes it possible to use the Azure Data Lake Storage Gen2 (ADLS) instead of HDFS. See the xref:hbase:usage-guide/adls.adoc[usage guide] for detailed information.
```

2024-11-21 10:58 UTC, Techassi commented on modules/ROOT/pages/release-notes.adoc
> +* The Stackable Operator for HDFS now supports upgrading existing HDFS installations. This process requires some manual intervention, however.
We should either add an (excerpt) of the manual steps required, or link to them.

2024-11-21 11:03 UTC, Techassi commented on modules/ROOT/pages/release-notes.adoc
> +* Apache NiFi: permit users to configure allowed hosts when NiFi is running behind a proxy. The proxy host check is now turned off by default. See documentation https://docs.stackable.tech/home/night
Slightly adjust wording, add xref link.

```suggestion
* Apache NiFi: Permit users to configure allowed hosts when NiFi is running behind a proxy. The proxy host check is disabled by default. See documentation xref:nifi:usage_guide/security#host-header-check[here].
```

Note: We should also rename `usage_guide` to `usage-guide` to be in line with newer conventions and other operators.

2024-11-21 11:57 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +* Listeners can now be configured to use either IP addresses or DNS hostnames.
I think hostname is more specific than a domain name (which is more like the suffix of a _domain_).
I think the original was more correct.

Maybe we need a third opinion to seal the deal?

2024-11-21 12:00 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +* Apache NiFi: permit users to configure allowed hosts when NiFi is running behind a proxy. The proxy host check is now turned off by default. See documentation https://docs.stackable.tech/home/night
Maybe the above suggestion still needs _now_.

I also separated sentences by newlines.

```suggestion
* Apache NiFi: Permit users to configure allowed hosts when NiFi is running behind a proxy.
  The proxy host check is now disabled by default.
  See documentation xref:nifi:usage_guide/security#host-header-check[here].
```

2024-11-21 12:06 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +* Apache Superset: Allow custom arbitrary python code in superset_config.py
I _think_ these should be formatted as inline code:

```suggestion
* Apache Airflow: Allow custom arbitrary python code in `webserver_config.py`.
* Apache Superset: Allow custom arbitrary python code in `superset_config.py`.
```

2024-11-21 12:13 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +* The group id of all files relevant to our products is now set to `0`. This allows the images to be used with any arbitrary user as every container user will always belong to the root group (`0`). T
I'd argue that the change is _required_ for moving to the `restricted-v2` SCC.
Add punkt, and split sentences to new lines.

```suggestion
* The group id of all files relevant to our products is now set to `0`.
  This allows the images to be run with an arbitrary user as every container user will always belong to the root group (`0`).
  This is required on OpenShift when migrating to the `restricted-v2` SecurityContextConstraint (SCC).
  Stackable currently defaults to the `nonroot-v2` SCC but we plan on migrating to the `restricted-v2` SCC in the future.
```

Also, is this statement true?

>   This allows the images to be run with an arbitrary user as every container user will always belong to the root group (`0`).

2024-11-21 12:15 UTC, maltesander commented on modules/ROOT/pages/release-notes.adoc
> +=== New / extended platform features
Yes added lukas input https://github.com/stackabletech/documentation/pull/679/commits/7c5cf1fb2a4b1c707a99be1d4314ceb9925d7bc6

2024-11-21 12:16 UTC, maltesander commented on modules/ROOT/pages/release-notes.adoc
> +> todo: do we mention NiFi 2.0.0 (experimental)? because NiFi 1.27.0 -> 2.0.0 requires manual intervention (basically same as in the 24.7 note)
I got the OIDC thing on my list, will add. Nifi 2.0.0 i would mention disabled reporting task and that the metrics endpoint it now requires authentication?

2024-11-21 12:20 UTC, maltesander commented on modules/ROOT/pages/release-notes.adoc
> +=== stackablectl
Thanks done in https://github.com/stackabletech/documentation/pull/679/commits/0a3701dcbfe0f89fd3dad06c89a2ff04613197ca. Still unsure about mentioning the PRs or not... 
Will consolidate in the end.

2024-11-21 12:21 UTC, maltesander commented on modules/ROOT/pages/release-notes.adoc
> +* The performance of the https://docs.stackable.tech/home/stable/hdfs/usage-guide/security.html#_authorization[OPA Authorizer] has been greatly improved. This _can_ be a breaking change so please mak
fixed in https://github.com/stackabletech/documentation/pull/679/commits/dde6742af142063add32d068e607b85cfc86086a

2024-11-21 12:22 UTC, maltesander commented on modules/ROOT/pages/release-notes.adoc
> +* Listeners can now be configured to use either IP addresses or DNS hostnames.
I think just `hostnames` would suffice?

2024-11-21 12:27 UTC, maltesander commented on modules/ROOT/pages/release-notes.adoc
> +* The Stackable Operator for HDFS now supports upgrading existing HDFS installations. This process requires some manual intervention, however.
done https://github.com/stackabletech/documentation/pull/679/commits/e70d4807a0ea5c40941ab56bce82d40a6138277c. 
We have some urls now pointing to "nightly".

2024-11-21 12:29 UTC, maltesander commented on modules/ROOT/pages/release-notes.adoc
> +* The group id of all files relevant to our products is now set to `0`. This allows the images to be used with any arbitrary user as every container user will always belong to the root group (`0`). T
pinging @lfrancke, came from here https://github.com/stackabletech/docker-images/pull/849#issuecomment-2414847380

2024-11-21 12:40 UTC, lfrancke commented on modules/ROOT/pages/release-notes.adoc
> +* The group id of all files relevant to our products is now set to `0`. This allows the images to be used with any arbitrary user as every container user will always belong to the root group (`0`). T
That statement is true, yeah.

2024-11-21 12:56 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +* The group id of all files relevant to our products is now set to `0`. This allows the images to be used with any arbitrary user as every container user will always belong to the root group (`0`). T
I'm curious how an arbitrary user is automatically part of the root group. Is that just for our images, or from some external base image? Or part of docker?

2024-11-21 13:06 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +* The cluster domain (default `cluster.local`) which caused problems in non-default cluster setups can now be configured in all operators using the ENV variable `KUBERNETES_CLUSTER_DOMAIN` or setting
```suggestion
* The cluster domain (default `cluster.local`) which caused problems in non-default cluster setups can now be configured in all operators using the ENV variable `KUBERNETES_CLUSTER_DOMAIN` or setting the helm value `kubernetesClusterDomain` during installation as described in https://docs.stackable.tech/home/nightly/guides/kubernetes-cluster-domain[Configuring the Kubernetes cluster domain].
```

2024-11-21 13:25 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +* Listeners can now be configured to use either IP addresses or DNS hostnames.
```suggestion
* Listeners can now be configured to use either IP addresses or fully qualified domain names (FQDNs).
```

2024-11-21 13:29 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +=== stackablectl
I think it is ok to link the PR if the desciption has useful information for end users.

But ideally, we want to just refer to the changelog (which links the PRs) and have automated changelogs (see https://github.com/stackabletech/decisions/issues/9).

2024-11-21 13:29 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +=== stackablectl
As discussed on a call, we will not link the PRs.

2024-11-21 13:32 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +* `4.15`
Marking as resolved, added an item to https://github.com/stackabletech/issues/issues/647

![image](https://github.com/user-attachments/assets/6a5fa60e-1cca-4a1a-b222-25c381582889)

2024-11-21 13:37 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +> todo: do we mention NiFi 2.0.0 (experimental)? because NiFi 1.27.0 -> 2.0.0 requires manual intervention (basically same as in the 24.7 note)
Just wanted to mention that a bunch of processors have been renamed (or have different class paths), and cannot be changed from the UI.

2024-11-21 13:44 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +=== New / extended platform features
Maybe this section can be about New platform features, and kept at a high level (logging, monitoring, authorization, etc..) and not operator specific stuff or fixes.

Instead, a second section can be about Improvements to the platform which can mention security/bug fixes.

Maybe headings like:

```adoc
=== New platform features

Improved Authentication::
In this release we introduced several authentication mechanisms in different products:
* Apache Airflow: https://github.com/stackabletech/airflow-operator/issues/337[OIDC support]
* Apache Kafka: https://github.com/stackabletech/kafka-operator/issues/655[Kerberos support]
* Apache NiFi: https://github.com/stackabletech/nifi-operator/issues/633[OIDC support]


...

=== Platform improvements

Vulnerabilities::
* More than 142 CVEs were fixed in the Stackable product images. This includes 11 critical and 55 high-severity CVEs.

...
```

2024-11-21 13:52 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +* More than 142 CVEs were fixed in the Stackable product images. This includes 11 critical and 55 high-severity CVEs.
```suggestion
* More than 142 CVEs were fixed in the Stackable product images.
  This includes 11 critical and 55 high-severity CVEs.
```

2024-11-21 14:14 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +=== New / extended platform features
Shuffled things around in 2a43d4a741a154ae2ee4f5d799a83c1c80be1f6b

2024-11-21 14:17 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +=== New / extended platform features
We happy?

![image](https://github.com/user-attachments/assets/d44513df-1ba8-4be8-b9e1-46700434a5da)

2024-11-22 11:30 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +* Apache NiFi: Permit users to configure allowed hosts when NiFi is running behind a proxy.
```suggestion
Nifi::

* Permit users to configure allowed hosts when NiFi is running behind a proxy.
* TODO: add comment about this: https://github.com/stackabletech/docker-images/pull/943

Misc::
```

2024-11-22 12:18 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +Bug fixes::
Todo: add in whatever comes out of:
- https://github.com/stackabletech/operator-rs/pull/909
- https://github.com/stackabletech/operator-rs/pull/910

Or the applicable changes that end up in the operators themselves.

2024-11-26 09:20 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +=== New / extended platform features
Done

2024-11-26 09:20 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +Bug fixes::
Added to the _Known issues_ section in 62e1943.

2024-11-26 09:22 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +* Apache NiFi: Permit users to configure allowed hosts when NiFi is running behind a proxy.
https://github.com/stackabletech/docker-images/pull/943 is now scheduled for 25.3

2024-11-26 09:29 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +However, this process requires some manual intervention as described https://docs.stackable.tech/home/nightly/hdfs/usage-guide/upgrading/[here].
Doc links must use xrefs so they point to the right release docs (instead of following nightly as it changes).

2024-11-26 09:30 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +However, this process requires some manual intervention as described https://docs.stackable.tech/home/nightly/hdfs/usage-guide/upgrading/[here].
Maybe this?

```suggestion
However, this process requires some manual intervention as described in xref:hbase:usage-guide/upgrading.adoc[Upgrading HDFS].
```

2024-11-26 09:31 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +However, this process requires some manual intervention as described https://docs.stackable.tech/home/nightly/hdfs/usage-guide/upgrading/[here].
Also look at other instances.

2024-11-26 09:45 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +* The performance of the https://docs.stackable.tech/home/stable/hdfs/usage-guide/security.html#\_authorization[OPA Authorizer] has been greatly improved.
```suggestion
* The performance of the xref:hdfs:usage-guide/security.html#_authorization[OPA Authorizer] has been greatly improved.
```

We just have to check if the link gets fumbled.

2024-11-26 09:46 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +* The User Info Fetcher HTTP API has been replaced with a Rego library. Please see https://docs.stackable.tech/home/nightly/opa/usage-guide/user-info-fetcher#_user_info_fetcher_api[user-info-fetcher
```suggestion
* The User Info Fetcher HTTP API has been replaced with a Rego library. Please see xref:opa:usage-guide/user-info-fetcher#_user_info_fetcher_api[user-info-fetcher API] for more information.
```

2024-11-26 09:51 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +  This _can_ be a breaking change so please make sure to read the hdfs-utils https://github.com/stackabletech/hdfs-utils/releases/tag/v0.4.0[release notes] for details.
This still displays strangely:

![image](https://github.com/user-attachments/assets/4647d6de-56f7-486f-b94f-5c5f3bda347e)

2024-11-26 09:55 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +The LTS version has in many cases also been adjusted in line with our https://docs.stackable.tech/home/stable/policies[support policy].
```suggestion
The LTS version has in many cases also been adjusted in line with our xref:ROOT:policies.adoc[support policy].
```

2024-11-26 10:41 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +  This <em>can</em> be a breaking change so please make sure to read the hdfs-utils https://github.com/stackabletech/hdfs-utils/releases/tag/v0.4.0[release notes] for details.
```suggestion
  This _can_ be a breaking change so please make sure to read the hdfs-utils https://github.com/stackabletech/hdfs-utils/releases/tag/v0.4.0[release notes] for details.
```

2024-11-26 10:52 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +* The performance of the xref:hdfs:usage-guide/security.adoc#_authorization[OPA Authorizer] has been greatly improved.
Escape the thing to fix this:

![image](https://github.com/user-attachments/assets/ddbeafe7-ea61-45f0-961b-a817ff726862)


```suggestion
* The performance of the xref:hdfs:usage-guide/security.adoc#\_authorization[OPA Authorizer] has been greatly improved.
```

2024-11-26 11:00 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +  This _can_ be a breaking change so please make sure to read the hdfs-utils https://github.com/stackabletech/hdfs-utils/releases/tag/v0.4.0[release notes] for details.
I am done this this!

```suggestion
  This can in some cases be a breaking change so please make sure to read the hdfs-utils https://github.com/stackabletech/hdfs-utils/releases/tag/v0.4.0[release notes] for details.
```

2024-11-26 11:23 UTC, adwk67 requested changes
Just a few small things. We used to have a section on breaking changes (e.g. https://docs.stackable.tech/home/stable/release-notes/#_breaking_changes and https://docs.stackable.tech/home/stable/release-notes/#_breaking_changes_2 and https://docs.stackable.tech/home/stable/release-notes/#_breaking_changes_3): is that not relevant for this release?

2024-11-26 11:23 UTC, adwk67 commented on modules/ROOT/pages/release-notes.adoc
> +* Added support for customizing `sAMAccountName` generation in secret operator.
Make this a sentence like the other elements in the list:
```suggestion
* Support has been added for customizing `sAMAccountName` generation in secret operator.
```

2024-11-26 11:23 UTC, adwk67 commented on modules/ROOT/pages/release-notes.adoc
> +* The RSA key length for generated key pairs now can be customized to 2048, 3072 and 4096 bits. The default is 2048 bit.
```suggestion
* The RSA key length for generated key pairs can now be customized to 2048, 3072 or 4096 bits. The default is 2048 bits.
```

2024-11-26 11:23 UTC, adwk67 commented on modules/ROOT/pages/release-notes.adoc
> +Apache NiFi: The ephemeral EmptyDir Volumes used to store log files before being aggregated have their size increased from a default of 33 MiB to 500 MiB.
We have mixed bullet/non-bullet lists, which is fine if we only have one element in a list. Is this one element or two?
```suggestion
Apache NiFi: The default size of ephemeral EmptyDir Volumes used to store log files before aggregation has been increased from 33 MiB to 500 MiB.
```

2024-11-26 11:23 UTC, adwk67 commented on modules/ROOT/pages/release-notes.adoc
> +Additionally the interval in which Logback checks if the maximum log file size has been reached was lowered from 60 seconds to 5 seconds.
```suggestion
Additionally the interval in which Logback checks if the maximum log file size has been reached has been reduced from 60 seconds to 5 seconds.
```

2024-11-26 11:23 UTC, adwk67 commented on modules/ROOT/pages/release-notes.adoc
> +Apache NiFi: Support disabling the create-reporting-task Job as well as podOverrides on that Job.
```suggestion
Apache NiFi: the create-reporting-task Job (and podOverrides on that Job) can now be disabled.
```

2024-11-26 11:23 UTC, adwk67 commented on modules/ROOT/pages/release-notes.adoc
> +* Trino, Spark, HBase, Airflow: These used to have https://github.com/stackabletech/issues/issues/548[issues] where config and environment variable overrides would not always work as expected, this h
```suggestion
* Trino, Spark, HBase, Airflow: The https://github.com/stackabletech/issues/issues/548[issues] where config and environment variable overrides did not work consistently have now been fixed.
```

2024-11-26 11:23 UTC, adwk67 commented on modules/ROOT/pages/release-notes.adoc
> +* We now provide additional completions for Nushell and Elvish, support using SOCK5 and HTTP proxies, and improved the sorting of release versions.
```suggestion
* We now provide additional completions for Nushell and Elvish, support using SOCK5 and HTTP proxies, and have improved the sorting of release versions.
```

2024-11-26 11:23 UTC, adwk67 commented on modules/ROOT/pages/release-notes.adoc
> +* Apache NiFi: For the experimental NiFi version `2.0.0`, the `PrometheusReportingTask`, use to activate a Prometheus metrics endpoint, was removed.
```suggestion
* Apache NiFi: For the experimental NiFi version `2.0.0`, the `PrometheusReportingTask` (which was used to activate a Prometheus metrics endpoint) has been removed.
```

2024-11-26 11:23 UTC, adwk67 commented on modules/ROOT/pages/release-notes.adoc
> +  NiFi now has its own API to directly access metrics. In contrast to previous versions, the metrics endpoints now requires authentication which is
```suggestion
  NiFi now has its own API to directly access metrics. In contrast to previous versions, the metrics endpoints now requires authentication.
```

2024-11-26 11:23 UTC, adwk67 commented on modules/ROOT/pages/release-notes.adoc
> +  not supported by the Stackable operator for Apache NiFi in this release.
```suggestion
  This is not supported by the Stackable operator for Apache NiFi in this release.
```

2024-11-26 11:48 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +=== Known issues
I still think we should mention that upgrading to NiFi 2.0.0 is not possible yet (due to some processors being renamed or having different class paths which cannot be changed from the UI).

2024-11-26 11:51 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +kubectl replace -f https://raw.githubusercontent.com/stackabletech/hello-world-operator/24.11.0/deploy/helm/hello-world-operator/crds/crds.yaml
We're thinking we should remove mentions of hello-world operator and product from release notes.

_Reiterating it in hopes that the above comment is no longer hidden_

2024-11-26 11:51 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +> todo: do we mention NiFi 2.0.0 (experimental)? because NiFi 1.27.0 -> 2.0.0 requires manual intervention (basically same as in the 24.7 note)
I added a comment on the updated version. Closing this.

2024-11-26 11:52 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +* The group id of all files relevant to our products is now set to `0`. This allows the images to be used with any arbitrary user as every container user will always belong to the root group (`0`). T
Ok, we'll leave the docs as they are.

2024-11-26 11:53 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +* Apache Druid: 26.0.0
This appears to be accidental, and would only appear in release notes from this version onwards (I think).

```suggestion
```

2024-11-26 12:01 UTC, NickLarsenNZ commented
> Just a few small things. We used to have a section on breaking changes (e.g. https://docs.stackable.tech/home/stable/release-notes/#_breaking_changes and https://docs.stackable.tech/home/stable/release-notes/#_breaking_changes_2 and https://docs.stackable.tech/home/stable/release-notes/#_breaking_changes_3): is that not relevant for this release?

@adwk67, We still do have the _Breaking changes_ section:
https://deploy-preview-679--stackable-docs.netlify.app/home/nightly/release-notes/#_breaking_changes

Maybe I misunderstood?

_Also noticed that the fragments are numbered but will take people to different content on each release. Not sure there is a way around it, without somehow getting the release in there._

2024-11-26 12:05 UTC, adwk67 commented
> > Just a few small things. We used to have a section on breaking changes (e.g. [docs.stackable.tech/home/stable/release-notes#_breaking_changes](https://docs.stackable.tech/home/stable/release-notes/#_breaking_changes) and [docs.stackable.tech/home/stable/release-notes#_breaking_changes_2](https://docs.stackable.tech/home/stable/release-notes/#_breaking_changes_2) and [docs.stackable.tech/home/stable/release-notes#_breaking_changes_3](https://docs.stackable.tech/home/stable/release-notes/#_breaking_changes_3)): is that not relevant for this release?
> 
> @adwk67, We still do have the _Breaking changes_ section: [deploy-preview-679--stackable-docs.netlify.app/home/nightly/release-notes#_breaking_changes](https://deploy-preview-679--stackable-docs.netlify.app/home/nightly/release-notes/#_breaking_changes)
> 
> Maybe I misunderstood?
> 
> _Also noticed that the fragments are numbered but will take people to different content on each release. Not sure there is a way around it, without somehow getting the release in there._

Ah, my bad, I missed that heading as I was looking for playbook-type code snippets showing before/after changes to resources. Maybe we don't need that this time.

2024-11-26 12:42 UTC, maltesander commented on modules/ROOT/pages/release-notes.adoc
> +  This can in some cases be a breaking change so please make sure to read the hdfs-utils https://github.com/stackabletech/hdfs-utils/releases/tag/v0.4.0[release notes] for details.
This is related to HDFS, which is not clear to me in this snippet.

2024-11-26 12:42 UTC, maltesander commented on modules/ROOT/pages/release-notes.adoc
> +Apache NiFi: the create-reporting-task Job (and podOverrides on that Job) can now be disabled.
This does not appear as a new "bullet" point in the preview:
![image](https://github.com/user-attachments/assets/77787fcd-c644-4ba6-b8db-d1d21ae4db32)

2024-11-26 12:42 UTC, maltesander commented on modules/ROOT/pages/release-notes.adoc
> +* Apache Spark Operator: Ensure Spark applications are submitted only once.
For consistency.
```suggestion
* Apache Spark: Ensure Spark applications are submitted only once.
```

2024-11-26 12:42 UTC, maltesander commented on modules/ROOT/pages/release-notes.adoc
> +* We now provide additional completions for Nushell and Elvish, support using SOCK5 and HTTP proxies, and have improved the sorting of release versions.
Is this really in the release? I remember it was merged after...

2024-11-26 12:42 UTC, maltesander commented on modules/ROOT/pages/release-notes.adoc
> +Hence, all Nodes must now have resolvable hostnames, or the NodePort ListenerClasses must be configured to set `.spec.preferredAddressType: IP`.
I will check again, it feels like one breaking change is not enough :D ?

2024-11-26 12:43 UTC, maltesander commented on modules/ROOT/pages/release-notes.adoc
> +* The performance of the xref:hdfs:usage-guide/security.adoc#\_authorization[OPA Authorizer] has been greatly improved.
Two idiots... https://github.com/stackabletech/documentation/pull/679#discussion_r1858463526 :D

2024-11-26 12:46 UTC, maltesander commented on modules/ROOT/pages/release-notes.adoc
> +=== Known issues
Hmm i think it **should** be possible starting from 1.27.0? Thats at least what they state in the nifi docs.
I would rather mention renamed processors (and keep an eye out for updating flows using this), instead of stating it does not work at all?

2024-11-26 12:54 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +Hence, all Nodes must now have resolvable hostnames, or the NodePort ListenerClasses must be configured to set `.spec.preferredAddressType: IP`.
Can someone help me rework this to the same _Breaking changes_ style as in the previous release notes?

_Since there is only one item, I have removed the unordered list_.

```suggestion
Of the changes mentioned above, the following are breaking (or could lead to breaking behaviour), and you will need to adapt your existing CRDs accordingly:

==== Listener operator

All ListenerClasses now default to using Fully Qualified Domain Names (FQDNs). 
Previously, NodePort ListenerClasses (such as external-unstable) would use the IP addresses.

All Nodes must now have resolvable hostnames, or the NodePort ListenerClasses must be configured with `spec.preferredAddressType: IP`.

.Breaking changes details
[%collapsible]
====
* `spec.preferredAddressType`: This now defaults to `HostnameConservative`, but can be set to `Hostname` or `IP`.
====
```

2024-11-26 12:55 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +Hence, all Nodes must now have resolvable hostnames, or the NodePort ListenerClasses must be configured to set `.spec.preferredAddressType: IP`.
Hmm yeah, sure there is more?

Please also see the reworked _Breaking changes_ section:
https://github.com/stackabletech/documentation/pull/679/files#r1858490497

2024-11-26 12:57 UTC, NickLarsenNZ commented
> > > Just a few small things. We used to have a section on breaking changes (e.g. [docs.stackable.tech/home/stable/release-notes#_breaking_changes](https://docs.stackable.tech/home/stable/release-notes/#_breaking_changes) and [docs.stackable.tech/home/stable/release-notes#_breaking_changes_2](https://docs.stackable.tech/home/stable/release-notes/#_breaking_changes_2) and [docs.stackable.tech/home/stable/release-notes#_breaking_changes_3](https://docs.stackable.tech/home/stable/release-notes/#_breaking_changes_3)): is that not relevant for this release?
> > 
> > 
> > @adwk67, We still do have the _Breaking changes_ section: [deploy-preview-679--stackable-docs.netlify.app/home/nightly/release-notes#_breaking_changes](https://deploy-preview-679--stackable-docs.netlify.app/home/nightly/release-notes/#_breaking_changes)
> > Maybe I misunderstood?
> > _Also noticed that the fragments are numbered but will take people to different content on each release. Not sure there is a way around it, without somehow getting the release in there._
> 
> Ah, my bad, I missed that heading as I was looking for playbook-type code snippets showing before/after changes to resources. Maybe we don't need that this time.

I have reworked the section to look like the previous releases. It is still a _code suggestion_:
https://github.com/stackabletech/documentation/pull/679/files#r1858490497

2024-11-26 12:58 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +Hence, all Nodes must now have resolvable hostnames, or the NodePort ListenerClasses must be configured to set `.spec.preferredAddressType: IP`.
Maybe we also want to link to the PR?

https://github.com/stackabletech/listener-operator/pull/244

2024-11-26 12:58 UTC, sbernauer commented on modules/ROOT/pages/release-notes.adoc
> +=== Known issues
I would second @maltesander. Some processors will break, but I'd say that's a customer problem and there is probably nothing we can (and will) do ^^
I fear all we can do is point to something like https://cwiki.apache.org/confluence/display/NIFI/Migrating+Deprecated+Components+and+Features+for+2.0.0#MigratingDeprecatedComponentsandFeaturesfor2.0.0-InvokeHTTP

2024-11-26 12:59 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +=== Known issues
I mean, it technically works, but since processors are renamed, they flow starts in a broken state which cannot easily be fixed - so I think it is worth warning people about it anyway.

2024-11-26 13:11 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +Apache NiFi: the create-reporting-task Job (and podOverrides on that Job) can now be disabled.
Fixed in: 83e56c0234e3ed3233b12052dacf043cb17232d5

2024-11-26 13:13 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +* Apache Kakfa: The bootstrap Kafka service is now included in https://github.com/stackabletech/kafka-operator/pull/741[certificate SANs].
```suggestion
* Apache Kafka: The bootstrap Kafka service is now included in https://github.com/stackabletech/kafka-operator/pull/741[certificate SANs].
```

2024-11-26 13:14 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +* We now provide additional completions for Nushell and Elvish, support using SOCK5 and HTTP proxies, and have improved the sorting of release versions.
It is in the stackablectl-24.11.1 release (it has similar release numbering, but is independent - yet still in these release notes :shrug: ).

2024-11-26 13:15 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +  This can in some cases be a breaking change so please make sure to read the hdfs-utils https://github.com/stackabletech/hdfs-utils/releases/tag/v0.4.0[release notes] for details.
Fixed in cd80f37

2024-11-26 13:19 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +kubectl replace -f https://raw.githubusercontent.com/stackabletech/hello-world-operator/24.11.0/deploy/helm/hello-world-operator/crds/crds.yaml
Done in 0141616

2024-11-26 13:27 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +Hence, all Nodes must now have resolvable hostnames, or the NodePort ListenerClasses must be configured to set `.spec.preferredAddressType: IP`.
I couldn't find a suitable place to link the PR, and I don't think it is too useful as a link in the release notes.

2024-11-26 13:32 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +=== Known issues
Done in 13342b71df4ce5c0646f3adeac09feb6938bfb87

2024-11-26 13:32 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
>  Support for OIDC with/without TLS has been added to Apache Druid in this release.
```suggestion
Support for OIDC with/without TLS has been added to Apache Druid in this release.

```

2024-11-26 13:37 UTC, adwk67 submitted a review, later dismissed

2024-11-26 14:07 UTC, NickLarsenNZ commented on modules/ROOT/pages/release-notes.adoc
> +====
@nightkr, @maltesander found some missing breaking changes from https://github.com/stackabletech/kafka-operator/pull/443

Are you able to please revise the wording to answer:
- What is the new format?
- What clients need to do exactly (restart, I assume)
- How to set the listenerClass manually (can be added to the collapsible section)
- Example of the upgrade process (where in the process does the STS get deleted, and how? cascade=false?)

2024-11-26 14:28 UTC, nightkr commented on modules/ROOT/pages/release-notes.adoc
> +====
Existing Kafka clusters will need to be migrated to using the Listener Operator. This is done by deleting the Kafka StatefulSet after the new Stackable Operator for Kafka has been installed, by running `kubectl delete StatefulSet --selector=app.kubernetes.io/managed-by=kafka.stackable.tech_kafkacluster`. The operator will then recreate it. However, note that the Kafka cluster will be unavailable during the procedure.

After the upgrade, Kafka clusters will default to only being accessible from *inside* the Kubernetes cluster. To make the cluster accessible from the outside, set `KafkaCluster.spec.brokers.config.bootstrapListenerClass: external-stable` and `KafkaCluster.spec.brokers.config.brokerListenerClass: external-unstable`. However, note that this upgrade will randomize the address that users will have to connect to, so any external clients must re-read it from the discovery configuration after the upgrade has been completed.

2024-11-26 14:29 UTC, nightkr commented on modules/ROOT/pages/release-notes.adoc
> +====
The one thing I'm unsure about is that paragraph 2 needs to be handled before 1 if applicable, but 1 sets up some of the background for why it's required. Maybe it would make sense to reorder that...

2024-11-26 14:31 UTC, maltesander commented on modules/ROOT/pages/release-notes.adoc
> +Hence, all Nodes must now have resolvable hostnames, or the NodePort ListenerClasses must be configured to set `.spec.preferredAddressType: IP`.
did not find more, will resolve this.

2024-11-26 14:39 UTC, nightkr commented on modules/ROOT/pages/release-notes.adoc
> +====
Oh right, that delete should be with `--all-namespaces`.

In theory you could do the delete with `--cascade=orphan`, but that's going to cause the StatefulSet controller to try to update the Pods in-place instead of doing a rollout, which is going to fail since Pods are largely immutable. You would then need to delete the pods manually one by one.

2024-11-26 14:49 UTC, maltesander commented on modules/ROOT/pages/release-notes.adoc
> +Misc::
Formal way. Or just go `CRDs`?
```suggestion
Miscellaneous::
```

2024-11-26 14:49 UTC, maltesander commented on modules/ROOT/pages/release-notes.adoc
> +Misc::
```suggestion
Miscellaneous::
```

2024-11-26 15:24 UTC, merged