Updated the Getting Started guide
stackabletech/documentation pull request #81
Opened 2021-08-13 12:15 UTC by Jimvin

2021-08-16 13:06 UTC, soenkeliebau requested changes
Some minor things, but overall great work!

2021-08-16 13:06 UTC, soenkeliebau commented on modules/ROOT/pages/getting_started.adoc
> +If all has gone well then you will have successfully deployed a Stackable cluster.
```suggestion
If all has gone well then you will have successfully deployed a Stackable cluster and used it to start three services that should now be ready for you.
```

2021-08-23 21:40 UTC, Jimvin reviewed
I've incorporated the suggestions in the latest updates.

2021-08-30 09:39 UTC, soenkeliebau requested changes
Just two really minor things

2021-08-30 09:39 UTC, soenkeliebau commented on modules/ROOT/pages/index.adoc
> +d and enabled.
Was this intentional?

2021-09-06 09:47 UTC, Jimvin reviewed
All the outstanding recommendations have been actioned, should be good to go.

2021-09-06 09:47 UTC, Jimvin commented on modules/ROOT/pages/index.adoc
> +d and enabled.
Removed the trailing sentence fragment.

2021-09-07 11:41 UTC, soenkeliebau approved these changes

2021-09-08 07:15 UTC, merged