Improve ubuntu installation path documentation
stackabletech/documentation pull request #89
Opened 2021-10-01 10:34 UTC by hikhvar

2021-10-01 10:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/stackabletech/documentation?pullRequest=89) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/stackabletech/documentation?pullRequest=89) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/stackabletech/documentation?pullRequest=89) it.</sub>

2021-10-04 07:26 UTC, teozkr requested changes
Hey, thanks for the PR! Ideally we shouldn't need the `[trusted=yes]` since that's a bit of a security regression (it disables the requirement for offline package signing). Apart from that, this LGTM.

2021-10-04 07:26 UTC, teozkr commented on modules/ROOT/pages/getting_started.adoc
> +    echo "deb [trusted=yes] https://repo.stackable.tech/repository/deb-dev buster main" > /etc/apt/sources.list.d/stackable.list
`[trusted=yes]` shouldn't be required, since you install the GPG key right above.

2021-10-04 09:50 UTC, hikhvar commented on modules/ROOT/pages/getting_started.adoc
> +    echo "deb [trusted=yes] https://repo.stackable.tech/repository/deb-dev buster main" > /etc/apt/sources.list.d/stackable.list
ok, I had a problem on my hetzner VMs, since they complain about a missing InRelease file in the repository. Can't reproduce on my current test setup. So maybe it was a temporary problem?

2021-10-04 10:45 UTC, hikhvar commented on modules/ROOT/pages/getting_started.adoc
> +    echo "deb [trusted=yes] https://repo.stackable.tech/repository/deb-dev buster main" > /etc/apt/sources.list.d/stackable.list
Error message was:
```
E: The repository 'https://repo.stackable.tech/repository/deb-dev buster Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

2021-10-04 14:06 UTC, teozkr commented on modules/ROOT/pages/getting_started.adoc
> +    echo "deb [trusted=yes] https://repo.stackable.tech/repository/deb-dev buster main" > /etc/apt/sources.list.d/stackable.list
Yeah, sounds like that was a temporary issue then. I can't reproduce this on Debian 10 or Ubuntu 20.04.

2021-10-04 16:17 UTC, hikhvar commented on modules/ROOT/pages/getting_started.adoc
> +    echo "deb [trusted=yes] https://repo.stackable.tech/repository/deb-dev buster main" > /etc/apt/sources.list.d/stackable.list
removed this, PTAL.

2021-10-05 07:08 UTC, teozkr approved these changes

2021-10-05 07:09 UTC, merged